### ISSUE TITLE
https://www.fastmock.site/ 的接口方便导出一份吗

### ISSUE THREAD

**Issue by mokedeng** [HalseySpicy/Geeker-Admin#10]
https://www.fastmock.site/ 的接口方便导出一份吗？公司内网访问不了，想重新部署一份，私发也ok：denyan7373@163.com
非常感谢

**Comment by HalseySpicy** [comment]
拉你了

**Comment by mokedeng** [comment]
> 拉你了

啥意思？怎么拉我的？没看懂啊

**Comment by HalseySpicy** [comment]
![image](https://user-images.githubusercontent.com/51069636/170409518-8db02866-c972-41c2-aa63-96015eae7040.png)

**Comment by mokedeng** [comment]
> ![image](https://user-images.githubusercontent.com/51069636/170409518-8db02866-c972-41c2-aa63-96015eae7040.png) fastmock

我还以为fastmock可以直接导出到postman使用，草率了

**Comment by zhupengfeivip** [comment]
@HalseySpicy 您好，把我也拉进去吧，这边我要写接口，需要知道原来接口返回的格式。和您的保持一致。
您先把我拉进fastmock吧，另外接口的问题能否考虑一下，估计很多人都会提出来。
