### ISSUE TITLE
Pro-Table组件有单独发包的想法吗

### ISSUE THREAD

**Issue by 1229984599** [HalseySpicy/Geeker-Admin#106]
感觉这样安装会更爽一点👻，作者大大，有想法吗？

**Comment by denganjia** [comment]
暂时没有，因为ProTable是基于ElementPlus的，单独发包后，你的项目也必须要用elementPlus

**Comment by HalseySpicy** [comment]
目前各种依赖太多，还是集成在项目里比较好使用，后期在考虑单独发包
