### ISSUE TITLE
【Feature Request】can update commitlint config for cz-git

### ISSUE THREAD

**Issue by Zhengqbbb** [HalseySpicy/Geeker-Admin#11]
Hi 我是 cz-git 的作者，很高兴看见你们使用 `cz-git`
我查看你们的配置和当前项目结构以及你们commit的习惯
发现其实配置文件可以参考一下，这个项目，会更好：
https://github.com/buqiyuan/vue3-antd-admin/blob/main/commitlint.config.js
但如果只是提供给用户自己修改的话，可以忽略我这个issue

🥳 如果有好的建议或者想法和我说~ 💡

**Comment by Zhengqbbb** [comment]
看家你也star了他的项目 你应该看过了 后面有什么需求就可以及时联系我~

**Comment by HalseySpicy** [comment]
好的，谢谢大佬的插件 😋
