### ISSUE TITLE
那个数据大屏一打开，电脑冒烟了，风扇狂转

### ISSUE THREAD

**Issue by ninyjun** [HalseySpicy/Geeker-Admin#113]
那个数据大屏一打开，电脑冒烟了，风扇狂转

**Comment by tlerbao** [comment]
实在不行把那个数据大屏相关的移除吧，一个标准Admin系统带数据大屏这种个性化需求的东西，作者属实有点安排的太全面了哈哈。

**Comment by denganjia** [comment]
啥子电脑哦，我18买的都没问题😂

ninyjun ***@***.***> 于 2023年1月5日周四 15:04写道：

**Comment by ninyjun** [comment]
> 啥子电脑哦，我18买的都没问题😂 ninyjun ***@***.***> 于 2023年1月5日周四 15:04写道：
> […](#)

macbookpro 因该还算可以吧

**Comment by HalseySpicy** [comment]
一般情况下 只有本地第一次打开的时候才会编译很久，线上预览的不会

**Comment by ninyjun** [comment]
> 一般情况下 只有本地第一次打开的时候才会编译很久，线上预览的不会

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/637581/211233757-7eac3717-b6cd-4b44-bd01-d41ebc5eef7f.png">
我就是线上预览的啊

**Comment by HalseySpicy** [comment]
开代理，部署在vercel 上
