### ISSUE TITLE
最近更新完代码后，tab页关闭比较卡顿

### ISSUE THREAD

**Issue by zhouxx** [HalseySpicy/Geeker-Admin#114]
特别是全部关闭卡顿更明显，麻烦看下是不是问题。

**Comment by HalseySpicy** [comment]
你好，这个问题是因为更新了vue 导致的，目前线上vue 版本是3.2.45，你可以退回到 3.2.37 就没这个问题了，好像是 vue 在更新 pinia 值的时候会卡顿，包括你切换主题也会卡顿，但是这个问题只会在开发的时候才会出现，打包之后就没这个问题了。

**Comment by HalseySpicy** [comment]
更新vue 版本，主要是因为vue 3.2.37存在一个很大的问题，使用transtion + keepalive 之后热更新刷新不会生效

**Comment by zhouxx** [comment]
OK，看后面是不是有版本都兼容

**Comment by HalseySpicy** [comment]
我这两天看了下这个问题，应该是更新 keepAlive 缓存数组产生的，只要更新 keepAliveStore.keepAliveName 的值，应该就会触发某些 keep-alive 组件的内部处理，导致页面很卡。你可以试试把 :include="keepAliveStore.keepAliveName" 注释掉，关闭 tabs 标签就不卡了
![image](https://user-images.githubusercontent.com/51069636/212260336-446089cf-1ecf-4c95-9580-8dc473622abc.png)

**Comment by zhouxx** [comment]
66 果然不卡了

**Comment by HalseySpicy** [comment]
@zhouxx 现在还卡吗，我的过年来就不卡了🤣，不去掉  :include="keepAliveStore.keepAliveName" 也不卡。我怀疑是 devtools 插件问题

**Comment by zhouxx** [comment]
@HalseySpicy   不卡了，不知道哪里修复了。
