### ISSUE TITLE
关于ProTable ColumnProps属性的多个下拉选项值enum改进

### ISSUE THREAD

**Issue by dmskys** [HalseySpicy/Geeker-Admin#119]
能不能通过一个接口获取当前标题筛选的所有下拉列表的接口，然后再根据prop name匹配，现在是每个下拉都需要提供一个接口，太麻烦了。如果自己通过api请求同一个接口，该如何操作设置enum？

**Comment by denganjia** [comment]
为什么不在页面上全部请求下来后，自己传递给enum属性呢。
```
let obj =  await someApi();

const columns = [
{label:"字段1",prop:"a",enum:obj['key1']},
{label:"字段2",prop:"b",enum:obj['key2']},
]
```

**Comment by dmskys** [comment]
这样用过，但是报错。说不支持异步函数

**Comment by denganjia** [comment]
> 这样用过，但是报错。说不支持异步函数

你在根组件里面包一层[suspense](https://cn.vuejs.org/guide/built-ins/suspense.html#suspense)组件就可以了

**Comment by dmskys** [comment]
> > 这样用过，但是报错。说不支持异步函数
> 
> 你在根组件里面包一层[suspense](https://cn.vuejs.org/guide/built-ins/suspense.html#suspense)组件就可以了

好的 谢谢！
