### ISSUE TITLE
如何在ProTable 搜索时，下拉列表不选择给一个默认值

### ISSUE THREAD

**Issue by dmskys** [HalseySpicy/Geeker-Admin#120]
由于status后台不传数据是0，所以需要在选择下拉筛选时，给一个默认值-1，如何操作？

**Comment by denganjia** [comment]
传`defaultValue`就行了
`columns.search.defaultValue`

**Comment by dmskys** [comment]
search: { el: "tree-select", props: { filterable: true }, defaultValue: -1} 下拉框会显示-1，我要的效果是显示请选中，传递给后台的值是-1
