### ISSUE TITLE
Expand的功能或者动作，可否合并到某个数据列

### ISSUE THREAD

**Issue by roubingxiong** [HalseySpicy/Geeker-Admin#121]
请教这个Expand的功能或者动作，可否合并到某个数据列。比如和用户名合并，我点一下用户名就可以伸展开
![image](https://user-images.githubusercontent.com/15197526/212643359-94fec88a-0315-45e5-b177-70a7fd6c62ce.png)

**Comment by HalseySpicy** [comment]
你可以看看 el-table 支持这样设置吗？如果可以的话 protable 应该就支持
