### ISSUE TITLE
项目可以在谷歌源代码中调试吗？

### ISSUE THREAD

**Issue by yubeihai** [HalseySpicy/Geeker-Admin#123]
新年快乐啊，感谢大佬的无私奉献，我想调试一个功能，加断点后断不到源代码，是要在哪里配置一下才可以吗？
![image](https://user-images.githubusercontent.com/20660983/215324057-28b8f14c-5652-44f6-b3a9-383a5d562dee.png)
在23行加的断点，会断到65行，然后执行方法的时候也会断到65行，23行并不会进断点。能问一下大佬这个是啥原因吗？
![image](https://user-images.githubusercontent.com/20660983/215324139-ba4602fe-7201-4e17-a40d-93b904ed7a95.png)

**Comment by HalseySpicy** [comment]
应该是 [vite-plugin-vue-setup-extend](https://github.com/vbenjs/vite-plugin-vue-setup-extend/issues/11) 插件引起的，你可以尝试使用 [vite-plugin-vue-setup-extend-plus](https://github.com/chenxch/vite-plugin-vue-setup-extend-plus)

**Comment by yubeihai** [comment]
感谢大佬，就是这个的问题，换成plus就可以调试了。
