### ISSUE TITLE
空状态塌陷了

### ISSUE THREAD

**Issue by xy1327462182** [HalseySpicy/Geeker-Admin#128]
表格的空状态塌陷了
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/68487774/218235805-fb711124-96de-4462-ab55-49d16b32b901.png">

**Comment by HalseySpicy** [comment]
你好，我不认为这是一个bug问题，因为 table 设置是 flex 布局，会根据窗口大小变化而变化，你可以尝试给 table 一个 min-height 属性
