### ISSUE TITLE
proTable很好用，但是。。。

### ISSUE THREAD

**Issue by wison-wu** [HalseySpicy/Geeker-Admin#129]
proTable很好用，但是我感觉还有一点要优化一下，就是右侧的工具栏，能够增加一个配置可以控制默认的四个展示其中部分，现在只能控制整个toolbar是否显示。部分场景下不太适用

**Comment by HalseySpicy** [comment]
你好。这个功能可根据自己需求自行扩展，在 protable 组件中 21-25 行可添加参数控制显隐
![image](https://user-images.githubusercontent.com/51069636/219529993-6c8190ec-0379-485e-9b64-d80ad534fe17.png)
