### ISSUE TITLE
protable表格 双击鼠标选中表格任意内容复制,去上方Search任意input框粘贴 或多出一到两个空格

### ISSUE THREAD

**Issue by zhangke1722** [HalseySpicy/Geeker-Admin#130]
1.protable表格 双击鼠标选中表格任意内容复制,去上方Search任意input框粘贴 或多出一到两个空格,  bug

2.集成右键复制表格内容也不错

**Comment by HalseySpicy** [comment]
你好，暂时没发现第一点这个问题呢
![动画](https://user-images.githubusercontent.com/51069636/219528842-c6ca9693-c975-4b8b-a422-8b5ec59e6abf.gif)

**Comment by zhangke1722** [comment]
> 你好，暂时没发现第一点这个问题呢 ![动画](https://user-images.githubusercontent.com/51069636/219528842-c6ca9693-c975-4b8b-a422-8b5ec59e6abf.gif) [ ![动画](https://user-images.githubusercontent.com/51069636/219528842-c6ca9693-c975-4b8b-a422-8b5ec59e6abf.gif) ](https://user-images.githubusercontent.com/51069636/219528842-c6ca9693-c975-4b8b-a422-8b5ec59e6abf.gif) [ ](https://user-images.githubusercontent.com/51069636/219528842-c6ca9693-c975-4b8b-a422-8b5ec59e6abf.gif)

![GIF 2023-2-17 10-04-06](https://user-images.githubusercontent.com/20833460/219531309-f3b437e5-8ba2-4fe5-95bf-16ab6164f742.gif)
貌似是用clearable后出现的

**Comment by HalseySpicy** [comment]
已去除前后空格
