### ISSUE TITLE
希望能分享一下该项目用到的vs code插件

### ISSUE THREAD

**Issue by cheekhan** [HalseySpicy/Geeker-Admin#131]
不太常用vs code，感觉好多插件功能之间好像互相冲突

**Comment by HalseySpicy** [comment]
{
	"recommendations": [
		"vue.volar",
		"vue.vscode-typescript-vue-plugin",
		"hollowtree.vue-snippets",
		"dbaeumer.vscode-eslint",
		"stylelint.vscode-stylelint",
		"esbenp.prettier-vscode",
		"editorconfig.editorconfig",
		"syler.sass-indented",
		"mikestead.dotenv",
		"akamud.vscode-theme-onedark",
		"emroussel.atomize-atom-one-dark-theme",
		"formulahendry.auto-rename-tag",
		"streetsidesoftware.code-spell-checker",
		"eamodio.gitlens",
		"spywhere.guides",
		"kisstkondoros.vscode-gutter-preview",
		"ritwickdey.liveserver",
		"techer.open-in-browser",
		"vscode-icons-team.vscode-icons"
	]
}

**Comment by HalseySpicy** [comment]
上面插件是我vscode装的，开发项目下面这几个就够了，项目里有建议
![image](https://user-images.githubusercontent.com/51069636/219533444-91f42fc5-1ea9-494a-81a8-34551699ab66.png)
