### ISSUE TITLE
SearchForm增加插槽功能

### ISSUE THREAD

**Issue by xiaoming16** [HalseySpicy/Geeker-Admin#134]
ProTable封装的真的很赞！大大提高了开发效率。 
但是实际项目中会有A，B，C；这类筛选框。C筛选框的值可能会依赖于B或者A。这种复杂的联动，通过参数配置很头疼。
还有就是一些筛选框的请求需要实时刷新，而不是进来的时候调用一次。
不知道能否添加一个插槽功能单独配置部分页面之间筛选框的联动。再次感谢大佬Table解决方案！！！

**Comment by xuebi2017** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，已收到您的邮件，谢谢！

**Comment by HalseySpicy** [comment]
树型 proTable 中包含上述功能。详情可以查看代码：https://admin.spicyboy.cn/#/proTable/treeProTable
