### ISSUE TITLE
插件更新

### ISSUE THREAD

**Issue by xmlgrg** [HalseySpicy/Geeker-Admin#135]
你好，项目使用的插件可以更新到新版本吗，有些插件的新版本有些用法是修改了~哈哈

**Comment by HalseySpicy** [comment]
axios、elemet-plus 已更新

**Comment by xmlgrg** [comment]
给力



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月03日 23:18 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HalseySpicy/Geeker-Admin] 插件更新 (Issue #135) |

axios、elemet-plus 已更新
