### ISSUE TITLE
table-column的formatter属性失效

### ISSUE THREAD

**Issue by lyc0209** [HalseySpicy/Geeker-Admin#136]
你好，我尝试使用proTable时发现table-column的formatter属性失效，具体表现为formatter函数传给了table-column，但是没有调用formatter函数，该列还是渲染的原始值。
![image](https://user-images.githubusercontent.com/51283456/221348924-3682d86f-02a6-42d0-9980-0b42d9ad9c13.png)
![image](https://user-images.githubusercontent.com/51283456/221348834-9a57aef9-6463-45bc-a943-914e3cd52082.png)

**Comment by lyc0209** [comment]
好吧，看了下源码，table-column有默认插槽的情况下没有机会调用formatter函数了😂

**Comment by HalseySpicy** [comment]
Render其实就可以替代formatter
