### ISSUE TITLE
多图片上传预览初始化异常

### ISSUE THREAD

**Issue by gamefake588** [HalseySpicy/Geeker-Admin#138]
1. 编辑、查看、新增在弹出Dialog组件中展示数据。

![01](https://user-images.githubusercontent.com/47933571/221793156-649eab07-855f-4664-93bb-cd497016e04a.png)

2. 编辑第一条数据时，数据正常，第二条开始数据不会发生变化，保持第一条数据不变

![02](https://user-images.githubusercontent.com/47933571/221793381-c9231405-ccd2-4d96-9f70-97536bc72994.png)

![03](https://user-images.githubusercontent.com/47933571/221793662-7f4ad89a-7662-493d-abbb-5c4d625b09d4.png)

**Comment by HalseySpicy** [comment]
你好，我这边暂时没出现这个问题呢，是我理解错误呢吗？
![image](https://user-images.githubusercontent.com/51069636/222058104-920b5e06-c1f2-4f63-9363-ec2b8b8c6b9e.png)

**Comment by gamefake588** [comment]
> 你好，我这边暂时没出现这个问题呢，是我理解错误呢吗？ ![image](https://user-images.githubusercontent.com/51069636/222058104-920b5e06-c1f2-4f63-9363-ec2b8b8c6b9e.png)

比如我在el-dialog组件中查看某条数据，进行渲染多图片组件时，第一条是正常的，查看到第二条开始它的fileList默认值不会变化，一直保持第一条的数据不改变。

**Comment by cryzyor** [comment]
![1678263909870](https://user-images.githubusercontent.com/24870752/223661564-b89ae050-7058-4090-80fd-c75e0f0284e2.jpg)
![1678263853058](https://user-images.githubusercontent.com/24870752/223661616-5105060e-9ca2-4138-9102-eac7ef0f4e39.jpg)
![1678263822567](https://user-images.githubusercontent.com/24870752/223661649-72684707-89d6-45ec-9547-0ad0a245623f.jpg)
大佬是我写错了吗？还是同一个问题，详情页通过onMounted获取详情后赋值给图片集，图片就不显示出来，

**Comment by gamefake588** [comment]
> ![1678263909870](https://user-images.githubusercontent.com/24870752/223661564-b89ae050-7058-4090-80fd-c75e0f0284e2.jpg) ![1678263853058](https://user-images.githubusercontent.com/24870752/223661616-5105060e-9ca2-4138-9102-eac7ef0f4e39.jpg) ![1678263822567](https://user-images.githubusercontent.com/24870752/223661649-72684707-89d6-45ec-9547-0ad0a245623f.jpg) 大佬是我写错了吗？还是同一个问题，详情页通过onMounted获取详情后赋值给图片集，图片就不显示出来，

这是我目前的解决办法，利用watch监听props进行重置。
![image](https://user-images.githubusercontent.com/47933571/223681953-8660006d-e212-4c29-8c01-36978aee89de.png)

**Comment by HalseySpicy** [comment]
已合并
