### ISSUE TITLE
ProTable columns搜索的一个bug

### ISSUE THREAD

**Issue by laravuel** [HalseySpicy/Geeker-Admin#142]
下面这种情况会导致这两个输入框双向绑定到同一个属性。

```
const columns = [
	{ prop: "name", label: "院系名称", align: "left", search: { el: "input" } },
	{
		prop: "university.name",
		label: "所属学校",
		align: "left",
		search: { el: "input" }
	}
]
```

![微信截图_20230310130713](https://user-images.githubusercontent.com/12763586/224229123-05a13fc2-0117-4645-9e1b-cd0e5f9d774c.png)

**Comment by HalseySpicy** [comment]
你好，我不认为这是一个bug问题。你搜索时不可能存在 两个 name，可以通过 SearchProps 的 key 属性指定
![image](https://user-images.githubusercontent.com/51069636/224233262-bf42f20d-e37a-47a5-bcf3-2f3f6adf1095.png)

**Comment by laravuel** [comment]
我又重新弄了下，确实可以，非常感谢！
