### ISSUE TITLE
Protable 列插槽里的方法为何会先触发一次？

### ISSUE THREAD

**Issue by erbao2001** [HalseySpicy/Geeker-Admin#143]
### 使用插槽自定义了 status 列，为何进入页面后还没点击这个el-switch，这个changeStatus方法就会先触发一次？
```
<template #status="scope">
    <el-switch v-model="scope.row.status" :active-value="1" :inactive-value="0" @change="changeStatus" />
</template>
```

```
const changeStatus = async (params: Job.ResJobList) => {
    // 进入页面就会先触发一次
}
```

**Comment by HalseySpicy** [comment]
使用 @click 代替，@change 事件在渲染 ProTable 时会默认会触发一遍

**Comment by erbao2001** [comment]
@HalseySpicy 插槽写法中用@click代替，也会有bug，点击后el-switch会先切换，然后弹出useHandleData提示，如果此时点取消，数据并没有变更，但是el-switch的开关已经变了

![iShot_2023-03-11_14 46 05](https://user-images.githubusercontent.com/123732260/224469710-32d80e08-d57f-48db-a69d-66fb7d65a42e.gif)


```
<template #tableHeader="">
    <el-button type="primary" :icon="CirclePlus" @click="openDialog('新增')" v-action="'job@save'">新增岗位</el-button>
</template>

const changeStatus = async (params: Job.ResJobList) => {
    await useHandleData(editJob, { id: params.id, status: params.status == 1 ? 0 : 1 }, `切换【${params.job_name}】部门状态`);
     proTable.value.getTableList();
};
```

**Comment by HalseySpicy** [comment]
使用  model-value 代替 v-model
![image](https://user-images.githubusercontent.com/51069636/224486842-add5d2a7-4e78-4903-940f-0c536b736d44.png)

**Comment by attachmentList** [comment]
这是bug吧
