### ISSUE TITLE
我想问下，protable的搜索区域有没有自定义插槽？

### ISSUE THREAD

**Issue by laravuel** [HalseySpicy/Geeker-Admin#144]
![微信截图_20230311111613](https://user-images.githubusercontent.com/12763586/224462164-31e0fcc7-11df-4f2e-8854-a0f8f4e13ea4.png)
就是我想自定义一个搜索项，放到搜索区域。有没有什么办法呢？

**Comment by HalseySpicy** [comment]
你可以新增一列 column，设置 isShow 属性为 false

**Comment by HalseySpicy** [comment]
![image](https://user-images.githubusercontent.com/51069636/224486920-584119e6-e708-4629-b90e-60ff502cc212.png)
