### ISSUE TITLE
TreeTable的默认样式能不能优化下？

### ISSUE THREAD

**Issue by erbao2001** [HalseySpicy/Geeker-Admin#148]
如图，这个层级缩进看起来有点别扭，二级太往左了，是否多缩进一些。

<img width="497" alt="image" src="https://user-images.githubusercontent.com/123732260/224939714-b13bb0c8-ac3d-4878-9f9c-b2339d5f67ac.png">

**Comment by HalseySpicy** [comment]
你可以设置 align: left 或者设置 proTable 的 indent 属性大小，
![image](https://user-images.githubusercontent.com/51069636/224952526-a40c0e85-aa37-4f8a-b4c7-b3af4e0c14cb.png)

**Comment by HalseySpicy** [comment]
el-table 支持的都支持
