### ISSUE TITLE
切换路由页面的时候 比较慢的原因

### ISSUE THREAD

**Issue by Corgis** [HalseySpicy/Geeker-Admin#15]
感谢作者提供的 开源admin框架，我有个疑惑
这个项目首次切换未访问过的路由 会有点慢 大概要等1-2秒 再次访问就能秒跳转 是为什么呢？

我看 vue-vben-admin 这个库的 预览地址 好像不会有这个问题。

谢谢答疑，再次感谢！！！

**Comment by HalseySpicy** [comment]
可能有以下几点原因：
1、目前项目放在对象存储上，资源访问比较慢。像数据大屏、数据可视化页面都会请求资源很久。
2、后台数据是使用在线mock平台，也会对其有影响
3、你可以直接执行 npm run build:pro 打包出来放在本地启项目，路由切换就会很快

**Comment by Corgis** [comment]
好的 了解了，感谢回复。。
