### ISSUE TITLE
transition-group使用mode属性会报警告

### ISSUE THREAD

**Issue by twb123** [HalseySpicy/Geeker-Admin#152]
Extraneous non-props attributes (mode) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.

**Comment by denganjia** [comment]
你的组件必须有一个根节点

**Comment by twb123** [comment]
<TransitionGroup> 支持和 <Transition> 基本相同的 props、CSS 过渡 class 和 JavaScript 钩子监听器，但有以下几点区别：

默认情况下，它不会渲染一个容器元素。但你可以通过传入 tag prop 来指定一个元素作为容器元素来渲染。

[过渡模式](https://cn.vuejs.org/guide/built-ins/transition.html#transition-modes)在这里不可用，因为我们不再是在互斥的元素之间进行切换。

列表中的每个元素都必须有一个独一无二的 key attribute。

CSS 过渡 class 会被应用在列表内的元素上，而不是容器元素上。

**Comment by twb123** [comment]
vue3文档上transition-group章节有写过渡模式在这里不可用

**Comment by zhangdesen** [comment]
transition-group配置个tag="span"
