### ISSUE TITLE
Menu handleClickMenu BUG

### ISSUE THREAD

**Issue by topcloud-xx** [HalseySpicy/Geeker-Admin#153]
/src/layouts/LayoutTransverse/index.vue
/src/layouts/components/Header/components/SearchMenu.vue
/src/layouts/components/Menu/SubMenu.vue

handleClickMenu方法中：
if (subItem.meta.isLink) return window.open(subItem.meta.isLink, "_blank");
应该修改为：
handleClickMenu 
if (subItem.meta.isLink) return window.open(subItem.path, "_blank");

**Comment by HalseySpicy** [comment]
isLink 没有问题啊

**Comment by erbao2001** [comment]
因为在 @HalseySpicy  的规划里 isLink如果为空就是false，如果有值就直接把isLink填写的值当url 打开，

而 @topcloud-xx 和我一样，给用户的添加菜单界面 isLink是个Switch 开关，值是真假01，这似乎更符合前端操作习惯，
如果isLink为证就把path当url打开哈哈，

所以他才会有这个疑问
<img width="717" alt="image" src="https://user-images.githubusercontent.com/123732260/226093367-da6cc80d-3142-4069-98b6-a01d49922181.png">

**Comment by topcloud-xx** [comment]
@erbao2001 是的，我也是如此处理的。感谢！
