### ISSUE TITLE
这里的类型为什么要这样写？为什么要继承下TableProps 然后再withDefaults(）？

### ISSUE THREAD

**Issue by hesuyang11** [HalseySpicy/Geeker-Admin#154]
![屏幕截图(10)](https://user-images.githubusercontent.com/40292517/226544819-4c0003c4-9144-4a12-9ce7-0d91f1bb1074.png)
![屏幕截图(11)](https://user-images.githubusercontent.com/40292517/226544823-d6179369-75e7-4776-859a-486e6cbbb5ff.png)

**Comment by HalseySpicy** [comment]
![image](https://user-images.githubusercontent.com/51069636/226545574-8a455dfd-54a3-465d-99a0-f38721021890.png)

**Comment by hesuyang11** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by HalseySpicy** [comment]
v-bind=”attrs“，继承一下 TableProps，ProTable 传参会有 el-table 参数的提示

**Comment by tlerbao2002** [comment]
ts属于一看就会，一用就蒙B
