### ISSUE TITLE
ProTable 的 expand 列的Bug

### ISSUE THREAD

**Issue by Wrendy** [HalseySpicy/Geeker-Admin#156]
在后端返回给ProTable的响应数据，当第一个属性有大写字母时，在expand列点击展开时，所有的列都全部展开

代码复现：

```vue
<template>
	<div class="table-box">
		<ProTable ref="proTable" title="测试" :columns="columns" :requestApi="getTableList">
			<!-- Expand -->
			<template #expand="scope">
				{{ scope.row }}
			</template>
		</ProTable>
	</div>
</template>

<script setup lang="ts">
import { ref, reactive } from "vue";
import { ResPage } from "@/api/interface/index";
import { ResultData } from "@/api/interface";
import { ColumnProps } from "@/components/ProTable/interface";
import ProTable from "@/components/ProTable/index.vue";

// 获取 ProTable 元素，调用其获取刷新数据方法（还能获取到当前查询参数，方便导出携带参数）
const proTable = ref();

interface TestList {
	testId: string;
	name: string;
}

const tableData = reactive<ResultData<ResPage<TestList>>>({
	code: "200",
	msg: "test table",
	data: {
		list: [
			{
				testId: "1",
				name: "张三"
			},
			{
				testId: "2",
				name: "李四"
			}
		],
		pageNum: 1,
		pageSize: 10,
		total: 10
	}
});

const getTableList = () => {
	return Promise.resolve(tableData);
};

// 表格配置项
const columns: ColumnProps<TestList>[] = [
	{ type: "expand", label: "Expand", width: 100 },
	{
		prop: "testId",
		label: "ID"
	},
	{
		prop: "name",
		label: "名称",
		search: { el: "input" }
	}
];
</script>

```

**Comment by denganjia** [comment]
> 在后端返回给ProTable的响应数据，当第一个属性有大写字母时，在expand列点击展开时，所有的列都全部展开
> 
> 代码复现：
> 
> ```
> <template>
> 	<div class="table-box">
> 		<ProTable ref="proTable" title="测试" :columns="columns" :requestApi="getTableList">
> 			
> 			<template #expand="scope">
> 				{{ scope.row }}
> 			</template>
> 		</ProTable>
> 	</div>
> </template>
> 
> <script setup lang="ts">
> import { ref, reactive } from "vue";
> import { ResPage } from "@/api/interface/index";
> import { ResultData } from "@/api/interface";
> import { ColumnProps } from "@/components/ProTable/interface";
> import ProTable from "@/components/ProTable/index.vue";
> 
> // 获取 ProTable 元素，调用其获取刷新数据方法（还能获取到当前查询参数，方便导出携带参数）
> const proTable = ref();
> 
> interface TestList {
> 	testId: string;
> 	name: string;
> }
> 
> const tableData = reactive<ResultData<ResPage<TestList>>>({
> 	code: "200",
> 	msg: "test table",
> 	data: {
> 		list: [
> 			{
> 				testId: "1",
> 				name: "张三"
> 			},
> 			{
> 				testId: "2",
> 				name: "李四"
> 			}
> 		],
> 		pageNum: 1,
> 		pageSize: 10,
> 		total: 10
> 	}
> });
> 
> const getTableList = () => {
> 	return Promise.resolve(tableData);
> };
> 
> // 表格配置项
> const columns: ColumnProps<TestList>[] = [
> 	{ type: "expand", label: "Expand", width: 100 },
> 	{
> 		prop: "testId",
> 		label: "ID"
> 	},
> 	{
> 		prop: "name",
> 		label: "名称",
> 		search: { el: "input" }
> 	}
> ];
> </script>
> ```

BUG原因跟大不大写没关系。
是因为ProTable默认传递给ElTable的rowKey为‘id’，但是你的表数据data里面没有id这个字段。
解决办法：

1. 设置ProTable的rowKey属性，覆盖默认的‘id’
2. 在数据中加入id字段

![image](https://user-images.githubusercontent.com/46669447/227073339-94915d1d-1202-4e28-a640-ae845d268df1.png)
![image](https://user-images.githubusercontent.com/46669447/227073402-c9d09c7f-50b5-4863-ac6c-c445e922da43.png)
