### ISSUE TITLE
我在proTable组件中渲染的icon图标为什么不能显示呢？

### ISSUE THREAD

**Issue by baiyishaoxia** [HalseySpicy/Geeker-Admin#165]
![image](https://user-images.githubusercontent.com/34636159/230283361-25a47090-e502-4a75-b73e-fe9adc833c4e.png)
![image](https://user-images.githubusercontent.com/34636159/230283489-98757a59-6990-4cda-a588-d09a29d93175.png)

**Comment by HalseySpicy** [comment]
component 组件用作用域插槽展示
