### ISSUE TITLE
ProTable 组件搜索区域联动

### ISSUE THREAD

**Issue by danwbj** [HalseySpicy/Geeker-Admin#166]
请教一下，搜索区域我想实现两个下拉框，其中一个的下拉数据依赖另一个下拉框的值做联动，要怎么实现

**Comment by HalseySpicy** [comment]
第一个搜索框 onChange 时更新第二个搜索框的 enum 数据就行了，注意：更新 enum 数据时必须操作原数组才能响应，不能直接赋值：
![image](https://user-images.githubusercontent.com/51069636/230580616-9b22d8d6-7a45-4b55-adf7-fd95a18e7e22.png)

**Comment by erbao2001** [comment]
这个应该写进常用技巧

**Comment by laravuel** [comment]
@HalseySpicy 不过这里边有一个问题，就是联动的下级已经选择了某个数据，这时候如果改变上级的数据，那么下级所选择的数据没法清空，还是之前选择的数据

**Comment by HalseySpicy** [comment]
> @HalseySpicy 不过这里边有一个问题，就是联动的下级已经选择了某个数据，这时候如果改变上级的数据，那么下级所选择的数据没法清空，还是之前选择的数据

proTable.value.searchParam.xxxx = ""

**Comment by laravuel** [comment]
> > @HalseySpicy 不过这里边有一个问题，就是联动的下级已经选择了某个数据，这时候如果改变上级的数据，那么下级所选择的数据没法清空，还是之前选择的数据
> 
> proTable.value.searchParam.xxxx = ""

非常感谢 🤞

**Comment by zscgxs** [comment]
> 第一个搜索框 onChange 时更新第二个搜索框的 enum 数据就行了，注意：更新 enum 数据时必须操作原数组才能响应，不能直接赋值： ![image](https://user-images.githubusercontent.com/51069636/230582193-2cecf1e0-020d-4ee7-a1ec-264533bd0b9e.png)

如果点击了重置，这个联动的下级下拉数据怎么清空呢

**Comment by HalseySpicy** [comment]
> > 第一个搜索框 onChange 时更新第二个搜索框的 enum 数据就行了，注意：更新 enum 数据时必须操作原数组才能响应，不能直接赋值： ![image](https://user-images.githubusercontent.com/51069636/230582193-2cecf1e0-020d-4ee7-a1ec-264533bd0b9e.png)
> 
> 如果点击了重置，这个联动的下级下拉数据怎么清空呢 <img alt="image" width="1198" src="https://user-images.githubusercontent.com/52776819/252898220-d5dff25f-807c-4409-945e-55928b9aee1d.png">

这样设置了，没清空吗？
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/6a041865-0d9b-4384-a431-07187369d824)

**Comment by zscgxs** [comment]
点击重置应该不会触发下拉框事件吧？

**Comment by zscgxs** [comment]
> > > 第一个搜索框 onChange 时更新第二个搜索框的 enum 数据就行了，注意：更新 enum 数据时必须操作原数组才能响应，不能直接赋值： ![image](https://user-images.githubusercontent.com/51069636/230582193-2cecf1e0-020d-4ee7-a1ec-264533bd0b9e.png)
> > 
> > 
> > 如果点击了重置，这个联动的下级下拉数据怎么清空呢 <img alt="image" width="1198" src="https://user-images.githubusercontent.com/52776819/252898220-d5dff25f-807c-4409-945e-55928b9aee1d.png">
> 
> 这样设置了，没清空吗？ ![image](https://user-images.githubusercontent.com/51069636/252929553-6a041865-0d9b-4384-a431-07187369d824.png)

点击重置后设置不了这个吧，重置按钮并不能自定义方法传入

**Comment by heavenly-zy** [comment]
> > > > 第一个搜索框 onChange 时更新第二个搜索框的 enum 数据就行了，注意：更新 enum 数据时必须操作原数组才能响应，不能直接赋值： ![image](https://user-images.githubusercontent.com/51069636/230582193-2cecf1e0-020d-4ee7-a1ec-264533bd0b9e.png)
> > > 
> > > 
> > > 如果点击了重置，这个联动的下级下拉数据怎么清空呢 <img alt="image" width="1198" src="https://user-images.githubusercontent.com/52776819/252898220-d5dff25f-807c-4409-945e-55928b9aee1d.png">
> > 
> > 
> > 这样设置了，没清空吗？ ![image](https://user-images.githubusercontent.com/51069636/252929553-6a041865-0d9b-4384-a431-07187369d824.png)
> 
> 点击重置后设置不了这个吧，重置按钮并不能自定义方法传入

可以改 proTable 源码，定义一个 resetCallback 执行重置后的一些操作，类似于 dataCallback 那样
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/50657815/3b1294b9-017e-4863-a192-ceebbbce17ee)

**Comment by HalseySpicy** [comment]
1.2.0 版本支持动态更新 columns，可直接赋值 enum，
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/aa914ddd-32d1-4bd7-8404-b465147b75ff)

**Comment by CocoLsp** [comment]
![Uploading 企业微信截图_17091875631004.png…]()

**Comment by CocoLsp** [comment]
![企业微信截图_17091875169428](https://github.com/HalseySpicy/Geeker-Admin/assets/88998635/1991b44b-838f-454f-bd6d-14b6a067328e)
![企业微信截图_17091875631004](https://github.com/HalseySpicy/Geeker-Admin/assets/88998635/399149c8-d7d0-4c8a-a998-06e1d99576e9)
请问除了这种方式还有其他方式控制搜索区域的搜索框显示和隐藏嘛

**Comment by CocoLsp** [comment]
请问有什么办法可以控制搜索区域中的搜索框的显示和隐藏嘛
