### ISSUE TITLE
右侧table的requestApi，动态根据左侧tree节点去替换

### ISSUE THREAD

**Issue by ccyarn** [HalseySpicy/Geeker-Admin#167]
大佬您好，右侧table的requestApi，动态根据左侧tree节点去替换，也就说table组件requestApi不同情况会有多个，现在只有一个，tree节点切换 initparams跟着切换，gettablelist这个方法触发，默认是第一个requestApi，现在有个需求tree节点不同，可能api也要跟着改变，这个时候传参也会改变，这个怎么处理

**Comment by denganjia** [comment]
> 大佬您好，右侧table的requestApi，动态根据左侧tree节点去替换，也就说table组件requestApi不同情况会有多个，现在只有一个，tree节点切换 initparams跟着切换，gettablelist这个方法触发，默认是第一个requestApi，现在有个需求tree节点不同，可能api也要跟着改变，这个时候传参也会改变，这个怎么处理

昨天在群里给你写了示例代码，你不看，你来发issue

**Comment by HalseySpicy** [comment]
![3ae6784e611e98e0dc20484d2b844a6](https://user-images.githubusercontent.com/51069636/231032375-65614400-aaa6-488c-b758-032a206a0081.png)
