### ISSUE TITLE
路由错误 Cannot read properties of undefined (reading '__asyncLoader') 

### ISSUE THREAD

**Issue by freer821** [HalseySpicy/Geeker-Admin#170]
如果连续点击左侧导航栏里面menu，会出现路由错误，然后不管点什么按钮都会报错，不知道各位是否有解决方法？
![image](https://user-images.githubusercontent.com/9664690/230992614-a4fcdf71-9cbe-4f17-b73e-9ac150e59c7a.png)

**Comment by xuebi2017** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，已收到您的邮件，谢谢！

**Comment by denganjia** [comment]
> 如果连续点击左侧导航栏里面menu，会出现路由错误，然后不管点什么按钮都会报错，不知道各位是否有解决方法？ ![image](https://user-images.githubusercontent.com/9664690/230992614-a4fcdf71-9cbe-4f17-b73e-9ac150e59c7a.png)

能否复现一下呢，我这边触发不了你这个错误

**Comment by HalseySpicy** [comment]
无法复现哦，或许是你浏览器插件造成的，你可以换个浏览器试试呢
