### ISSUE TITLE
当首页含有子菜单时，左侧菜单没有默认展开

### ISSUE THREAD

**Issue by erbao2001** [HalseySpicy/Geeker-Admin#172]
![CleanShot 2023-04-13 at 10 22 47](https://user-images.githubusercontent.com/123732260/231631195-1762775d-42e5-4885-953b-357dcbcd5de3.gif)

首页含有子菜单时，进入系统没有默认展开，这个应该怎么做？

**Comment by HalseySpicy** [comment]
你代码也不截个吗？

**Comment by erbao2001** [comment]
@HalseySpicy 没啥代码啊，你默认首页不是没有子菜单吗，我就是在首页下添加了子菜单，进入系统他不会默认展开，宝贝
没改任何代码，就是加了个子菜单

**Comment by HalseySpicy** [comment]
我的也没问题啊
![image](https://user-images.githubusercontent.com/51069636/231633487-bdafe24b-30b3-4308-b62a-6f88e9cc7e6d.png)
![image](https://user-images.githubusercontent.com/51069636/231633542-a14abb1c-4d6d-4927-89fb-301296ba45bf.png)

**Comment by erbao2001** [comment]
@HalseySpicy 可以了可以了，我去看了一下
![CleanShot 2023-04-13 at 10 39 03@2x](https://user-images.githubusercontent.com/123732260/231633723-49db2cb0-7732-417b-acc4-b59b68be2995.png)
红框标注之前没给path哈哈，虽然path没用，也得给

**Comment by HalseySpicy** [comment]
👍

**Comment by erbao2001** [comment]
@HalseySpicy 借这个issues 问个问题哈，正好你在
使用图标的页面都要各种引入，能不能直接用哈，有几种解法？
```
import { Message, Position, Postcard, SetUp, Edit, Delete, Rank, Stopwatch, Monitor, Search } from "@element-plus/icons-vue";
```
