### ISSUE TITLE
ProTable formatter不生效

### ISSUE THREAD

**Issue by b-I-r-d** [HalseySpicy/Geeker-Admin#174]
大佬你好，最近在使用ProTable的过程中发现formatter不生效，麻烦帮忙看一下是哪里写的不对吗？
![image](https://user-images.githubusercontent.com/13044069/232489389-0bc60fbe-a1e3-4017-859c-e2b63c35a198.png)

这里的需求就是想把size从字节转换成mb输出，想到用formatter，但是没有起作用，上面的方法没有跑到。

谢谢！

**Comment by HalseySpicy** [comment]
是的，el-table 使用了插槽之后 formatter 不会生效，render 也可以直接返回函数进行数据处理
