### ISSUE TITLE
折叠菜单时，最下面的菜单（大概3个）会向上展示，这是BUG吗？

### ISSUE THREAD

**Issue by 154425897** [HalseySpicy/Geeker-Admin#175]
![image](https://user-images.githubusercontent.com/95684914/232643922-d4bcde19-afba-4976-ba70-1813c77d1252.png)

**Comment by denganjia** [comment]
> ![image](https://user-images.githubusercontent.com/95684914/232643922-d4bcde19-afba-4976-ba70-1813c77d1252.png)

这个是正常的啊，它往下显示不了就会往上显示。

**Comment by HalseySpicy** [comment]
正常的，elment 内部判断的

**Comment by 154425897** [comment]
如果弹窗的子菜单层比屏幕高时就会出现滚动条，整个页面都会错乱：
![image](https://user-images.githubusercontent.com/95684914/232714307-aec89a34-bf97-4cb6-9a97-d6b111be902d.png)

**Comment by HalseySpicy** [comment]
你可以给 element-plus 提交 pr
