### ISSUE TITLE
Elementuiplus 建议加上自动引入

### ISSUE THREAD

**Issue by AngusYe** [HalseySpicy/Geeker-Admin#177]
大佬，Elementuiplus 建议加上自动引入

**Comment by denganjia** [comment]
> 大佬，Elementuiplus 建议加上自动引入

自动引入？自动引入后ProTable组件就用不了了

**Comment by HalseySpicy** [comment]
compoent 标签渲染的组件 自动引入不会识别的
![image](https://user-images.githubusercontent.com/51069636/232961444-9bdea2ec-4d32-4d48-83d9-d88e36aab221.png)

**Comment by trentyc** [comment]
用上 unplugin-vue-components  应该可以解决
