### ISSUE TITLE
动态tableColumns怎么处理？

### ISSUE THREAD

**Issue by cc932636456** [HalseySpicy/Geeker-Admin#179]
hi，tableColumns刚开始为空，接口请求回来的tableColumns重新赋值，页面不会更新

**Comment by denganjia** [comment]
啊这......为什么要动态tableColumns啊

**Comment by cc932636456** [comment]
因为col是后端返回来的，这个业务场景应该有不少吧，tablecol初始是空，请求完之后返回col，赋值，然后表格不显示



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月20日(星期四) 中午11:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HalseySpicy/Geeker-Admin] 动态tableColumns怎么处理？ (Issue #179)





 
啊这......为什么要动态tableColumns啊

**Comment by denganjia** [comment]
> 因为col是后端返回来的，这个业务场景应该有不少吧，tablecol初始是空，请求完之后返回col，赋值，然后表格不显示
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月20日(星期四) 中午11:47 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HalseySpicy/Geeker-Admin] 动态tableColumns怎么处理？ (Issue #179) 啊这......为什么要动态tableColumns啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

说实话，你这个需求是我从业这么多年第一次看到😵

**Comment by cc932636456** [comment]
数据字典不都这么处理的吗 0 0 我两家公司都是这样的，你们之前列都是前端写死的么？ 这种后端返回col的情况我们的protable好像就不支持了吧？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月20日(星期四) 中午1:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HalseySpicy/Geeker-Admin] 动态tableColumns怎么处理？ (Issue #179)





  
因为col是后端返回来的，这个业务场景应该有不少吧，tablecol初始是空，请求完之后返回col，赋值，然后表格不显示
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月20日(星期四) 中午11:47 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [HalseySpicy/Geeker-Admin] 动态tableColumns怎么处理？ (Issue #179) 啊这......为什么要动态tableColumns啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
说实话，你这个需求是我从业这么多年第一次看到😵

**Comment by denganjia** [comment]
> 数据字典不都这么处理的吗 0 0 我两家公司都是这样的，你们之前列都是前端写死的么？ 这种后端返回col的情况我们的protable好像就不支持了吧？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月20日(星期四) 中午1:46 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HalseySpicy/Geeker-Admin] 动态tableColumns怎么处理？ (Issue #179) 因为col是后端返回来的，这个业务场景应该有不少吧，tablecol初始是空，请求完之后返回col，赋值，然后表格不显示 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月20日(星期四) 中午11:47 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [HalseySpicy/Geeker-Admin] 动态tableColumns怎么处理？ (Issue #179) 啊这......为什么要动态tableColumns啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 说实话，你这个需求是我从业这么多年第一次看到😵 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以支持
```vue
<template>
  <div class="table-box">
    <ProTable ref="proTable" title="用户列表" :key="key" :columns="columns" :request-api="getTableList"> </ProTable>
  </div>
</template>

<script setup lang="tsx" name="testProTable">
import { onMounted, ref } from "vue";
import { ColumnProps } from "@/components/ProTable/interface";
import ProTable from "@/components/ProTable/index.vue";

const columns = ref<Partial<ColumnProps[]>>([]);

//请求数据
const getTableList = async (p: any) => {
  console.log(p);
  return await Promise.resolve({
    code: 200,
    data: {
      list: [{ name: "张三" }, { age: 1998 }],
      total: 1,
      pageNum: 1,
      pageSize: 10
    }
  });
};
// 请求columns
const getColumns = async () => {
  console.log("getColumns");

  return await Promise.resolve<Partial<ColumnProps[]>>([
    { label: "姓名", prop: "name" },
    { label: "年龄", prop: "age" }
  ]);
};
const key = ref("key");
onMounted(async () => {
  columns.value = await getColumns();
  key.value = "key2";
});
</script>

```
给组件一个Key，然后再获取到col后修改key，使组件重新渲染就行了

**Comment by cc932636456** [comment]
谢谢大佬，可以解决，为什么修改key就能重新渲染，我没明白可以帮忙解释一下原理吗，另外你们那边table列没遇到动态的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月20日(星期四) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HalseySpicy/Geeker-Admin] 动态tableColumns怎么处理？ (Issue #179)





  
数据字典不都这么处理的吗 0 0 我两家公司都是这样的，你们之前列都是前端写死的么？ 这种后端返回col的情况我们的protable好像就不支持了吧？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月20日(星期四) 中午1:46 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [HalseySpicy/Geeker-Admin] 动态tableColumns怎么处理？ (Issue #179) 因为col是后端返回来的，这个业务场景应该有不少吧，tablecol初始是空，请求完之后返回col，赋值，然后表格不显示 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月20日(星期四) 中午11:47 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [HalseySpicy/Geeker-Admin] 动态tableColumns怎么处理？ (Issue #179) 啊这......为什么要动态tableColumns啊 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 说实话，你这个需求是我从业这么多年第一次看到😵 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
可以支持
 <template&gt;   <div class="table-box"&gt;     <ProTable ref="proTable" title="用户列表" :key="key" :columns="columns" :request-api="getTableList"&gt; </ProTable&gt;   </div&gt; </template&gt; <script setup lang="tsx" name="testProTable"&gt; import { onMounted, ref } from "vue"; import { ColumnProps } from "@/components/ProTable/interface"; import ProTable from "@/components/ProTable/index.vue";  const columns = ref<Partial<ColumnProps[]&gt;&gt;([]);  //请求数据 const getTableList = async (p: any) =&gt; {   console.log(p);   return await Promise.resolve({     code: 200,     data: {       list: [{ name: "张三" }, { age: 1998 }],       total: 1,       pageNum: 1,       pageSize: 10     }   }); }; // 请求columns const getColumns = async () =&gt; {   console.log("getColumns");    return await Promise.resolve<Partial<ColumnProps[]&gt;&gt;([     { label: "姓名", prop: "name" },     { label: "年龄", prop: "age" }   ]); }; const key = ref("key"); onMounted(async () =&gt; {   columns.value = await getColumns();   key.value = "key2"; }); </script&gt; 
 
给组件一个Key，然后再获取到col后修改key，使组件重新渲染就行了

**Comment by cc932636456** [comment]
发现个问题，这样好像会多次请求了，我的动态列其实就是requestApi那个接口返回来的，

**Comment by HalseySpicy** [comment]
requestApi 不返回的表格数据吗，跟 tablecolumn 有什么关系

> 发现个问题，这样好像会多次请求了，我的动态列其实就是requestApi那个接口返回来的，

**Comment by HalseySpicy** [comment]
你加微信吧

**Comment by tlerbao** [comment]
确实有的项目是这么干的，纯后端年代为了不写模板代码，后端直接builder出相应的form和table，现在前后端分离时代了，还想用后端生成，不那么分离哈，我用的上一个admin里面就带一个table组件，前端代码就import这个组件给两个optinos就行了， table col和 Table data都是后端返回。
