### ISSUE TITLE
组件 bug(格式化问题)

### ISSUE THREAD

**Issue by wsm1025** [HalseySpicy/Geeker-Admin#18]
估摸着插件格式化问题 
具体页面:   超级表格使用 component
具体代码：src/components/ProTable/index.vue 85-91

格式化一下即可

**Comment by HalseySpicy** [comment]
你好，我这目前是没有问题的，不知道是不是编辑器插件问题
![微信截图_20220619190015](https://user-images.githubusercontent.com/51069636/174477715-bb9d1e2c-2974-474c-9123-538800f7c9a2.png)

**Comment by wsm1025** [comment]
<img width="871" alt="截屏2022-06-19 21 05 43" src="https://user-images.githubusercontent.com/64190019/174482471-09e42fc3-0177-415b-bd7c-062ad157023a.png">
<img width="992" alt="截屏2022-06-19 21 06 10" src="https://user-images.githubusercontent.com/64190019/174482502-991f0dee-a55b-423a-a5bc-6d817c55fcaa.png">
就是格式化问题了
