### ISSUE TITLE
ProTable 组件搜索区域组件可以自定义吗

### ISSUE THREAD

**Issue by zscgxs** [HalseySpicy/Geeker-Admin#182]
类似这种
![image](https://user-images.githubusercontent.com/52776819/233824314-a24cd751-b90d-46e7-9f80-f576c660cde2.png)

**Comment by HalseySpicy** [comment]
目前不支持

**Comment by zhaoyunqi888** [comment]
建议后期增加此功能 这种需求还比较多 比如 年龄查询 需要年龄段

**Comment by HalseySpicy** [comment]
@zscgxs 下个版本更新 tsx 组件支持
![image](https://user-images.githubusercontent.com/51069636/236615665-2fafeabf-f64f-4de5-a052-d873754429b6.png)

**Comment by HalseySpicy** [comment]
已更新
