### ISSUE TITLE
会出现两个tabs，把缓存都清了还是存在，但放置一段时间再刷新又好了

### ISSUE THREAD

**Issue by kaizi311** [HalseySpicy/Geeker-Admin#183]
![a9a12ab075be64f1388f400ba1d26a0](https://user-images.githubusercontent.com/49019078/233891718-08c5c049-9349-4b47-b857-ce8fa56d0a53.png)

**Comment by HalseySpicy** [comment]
无法复现，你可以查看两个 首页tabs 数据是否一样
