### ISSUE TITLE
tabs更多按钮刷新选项是刷新所有tabs页面，还是当前高亮tab？

### ISSUE THREAD

**Issue by Y-Lao** [HalseySpicy/Geeker-Admin#184]
![image](https://user-images.githubusercontent.com/103941257/233962979-3b8b40bb-d4f4-44d1-ac6c-4664b8842a18.png)
如果只想刷新当前高亮tab，这个能实现吗？

**Comment by HalseySpicy** [comment]
目前就是刷新的当前高亮tab
