### ISSUE TITLE
ProTable 组件在使用时候，遇到BigInteger类型时候报错

### ISSUE THREAD

**Issue by lmabbe** [HalseySpicy/Geeker-Admin#187]
使用json-bigint这个组件，把返回的Long数据转成BigInteger时，在table渲染时候出错。
![image](https://user-images.githubusercontent.com/45346209/234792504-ec7e44c3-ec02-407b-ab87-c8a9d03e10a6.png)

![image](https://user-images.githubusercontent.com/45346209/234792682-692c6eaf-e87c-446f-8e6e-1d6b37673039.png)

**Comment by lmabbe** [comment]
![image](https://user-images.githubusercontent.com/45346209/234792869-80a1ef69-912b-4bf5-af4f-75a8d50f3aca.png)

这个是转换的处理

**Comment by HalseySpicy** [comment]
你好，这个应该是 el-table 内部报的错误吧？

**Comment by HalseySpicy** [comment]
可以单独使用 el-table 看看报错吗，如果报错，可以向 element-plus 官方提交 issues
