### ISSUE TITLE
建议搜索 区域增加自定义查询功能

### ISSUE THREAD

**Issue by zhaoyunqi888** [HalseySpicy/Geeker-Admin#189]
建议SearchForm 区域增加自定义查询功能
如 年龄查询 需要年龄段 查询  XX 至 XX 这样。

**Comment by HalseySpicy** [comment]
等我想想这个功能怎么添加比较好，或者你有更好的建议，可以告诉我

**Comment by zhaoyunqi888** [comment]
在掘金中看到一个帖子有如下代码 但个人初学前段 不会改在故把代码贴出来 看能否提供灵感：
<pro-table
    :label-width="110"
    headerTitle="用户列表"
    :request="handleRequest"
    :columns="columns"
>
  <template #search>//slot名跟cloumns中search配置对应
    <el-radio-group>
        <el-radio-button label="全部"/>
        <el-radio-button label="本周"/>
        <el-radio-button label="本月"/>
    </el-radio-group>
  </template>
</pro-table>

对应的cloumns中配置：

{
  label: "自定义搜索",
  search: {
    slot: "search"//跟slot名对应
  }
}

在搜索列对应页面：

if (item.search?.slot) {
        return _this?.slots?.[item?.search?.slot]?.()
}

掘金地址：https://juejin.cn/post/7182879856332374076

gitee代码地址：https://gitee.com/tian_may/easy-table/tree/master

**Comment by HalseySpicy** [comment]
我大概看了下，可以支持 tsx 组件渲染，插槽的话改动太大，需要将 SearchFormItem 组件整个重新，下个版本更新 tsx 组件支持
![image](https://user-images.githubusercontent.com/51069636/236615577-03ae94f1-0baf-4831-a5e5-4ccc66bae9d0.png)

**Comment by zhaoyunqi888** [comment]
楼主 V5

**Comment by HalseySpicy** [comment]
已更新
