### ISSUE TITLE
这个组件的报错,无法打包,如何处理呢?

### ISSUE THREAD

**Issue by szjhtz** [HalseySpicy/Geeker-Admin#190]
![微信截图_20230505060812](https://user-images.githubusercontent.com/500123/236340806-821b76d6-b1e6-4965-8a75-4bd4a9460ce8.png)
![微信截图_20230505061310](https://user-images.githubusercontent.com/500123/236340896-9ed78014-32ce-46f5-ac01-6d10ad62211a.png)

**Comment by HalseySpicy** [comment]
这个是 volar 版本检测错误，目前我一直使用 1.2.0 版本没问题，

**Comment by HalseySpicy** [comment]
或者可以直接去掉代码检查，在打包
![image](https://user-images.githubusercontent.com/51069636/236599723-2cbe7861-946a-4332-8817-f2c05bb316e8.png)

**Comment by HalseySpicy** [comment]
https://github.com/vuejs/language-tools/issues/3136

**Comment by HalseySpicy** [comment]
已更新
