### ISSUE TITLE
建议按钮权限这块采用 **:**:** 的匹配方式

### ISSUE THREAD

**Issue by Ikarows** [HalseySpicy/Geeker-Admin#191]
例如 system:user:add

**Comment by HalseySpicy** [comment]
system:user:add 这个应该是后端配置按钮权限的授权字符串格式吧，我们后端目前就是这样反的
![image](https://user-images.githubusercontent.com/51069636/236615801-fa4de9b0-3da4-456b-8eff-e335888f8480.png)

**Comment by HalseySpicy** [comment]
根据自己需求改造就行了

**Comment by Ikarows** [comment]
> 

ok

**Comment by Ikarows** [comment]
> 根据自己需求改造就行了

ok
