### ISSUE TITLE
打包编译错误

### ISSUE THREAD

**Issue by hcxmj** [HalseySpicy/Geeker-Admin#193]
执行yarn build:pro的时候报错提示如下：
Property 'default' does not exist on type '{}'.
<img width="944" alt="image" src="https://user-images.githubusercontent.com/58494807/236751251-2ee2a5e1-3927-4674-b2f6-86a7cbdb5349.png">

**Comment by HalseySpicy** [comment]
https://github.com/HalseySpicy/Geeker-Admin/issues/190

**Comment by HalseySpicy** [comment]
也可以拉取最新代码解决

**Comment by hcxmj** [comment]
> 也可以拉取最新代码解决
好的，谢谢！

**Comment by DaveLeeBoy** [comment]
> 也可以拉取最新代码解决

你好，最新代码里是如何解决的。我升级了volar的版本和vue-tsc 还是同样的报错
