### ISSUE TITLE
node18版本build:test检验报错

### ISSUE THREAD

**Issue by xiuyuan-wang** [HalseySpicy/Geeker-Admin#194]
Build:test校验报错。node18.16.0. 在linux环境下
![Uploading EB1C411F-FFAA-48B4-BA05-AE4879EDC0D9.jpeg…]()

**Comment by xiuyuan-wang** [comment]
![IMG_5660](https://user-images.githubusercontent.com/15852591/236781438-4c683d7c-0932-4401-a8f4-6a5a5f4ba641.JPG)

**Comment by HalseySpicy** [comment]
拉最新代码，或者看这里 https://github.com/HalseySpicy/Geeker-Admin/issues/190
