### ISSUE TITLE
pnpm和npm执行install后运行不一致。

### ISSUE THREAD

**Issue by xiuyuan-wang** [HalseySpicy/Geeker-Admin#197]
![IMG_5681](https://github.com/HalseySpicy/Geeker-Admin/assets/15852591/f3a1d2a4-4861-42e3-8d0d-008776eb0351)
![IMG_5682](https://github.com/HalseySpicy/Geeker-Admin/assets/15852591/31e34dd4-ac54-492f-a527-a85473a8bdf7)

**Comment by xiuyuan-wang** [comment]
npm 有问题。 
代码protable属性
rowKey="taskId"
:tree-props="{children: 'subTaskList'}"

**Comment by HalseySpicy** [comment]
npm 没有 lock，用 pnpm 安装

**Comment by xiuyuan-wang** [comment]
感觉这个关系不大吧，我看了包都是2.3.4 排查好久，想知道具体啥影响的

**Comment by HalseySpicy** [comment]
关系肯定大啊，没锁版本，假如是 2.3.4，npm i 能安装到 2.3.9 版本去，可以先去了解了解 lock 作用吧

**Comment by xiuyuan-wang** [comment]
我在node_modules 里看了element plus版本了 都是2.3.4

**Comment by tlerbao** [comment]
所以1.0为何删除了lock文件，lock是建议提交到仓库的，php的composer也是建议lock提交到仓库的
这样能最大限度的，保证团队开发的版本一致性，开源项目，更是避免了npm i的时候小伙伴们安装了太新的包不兼容哈

**Comment by HalseySpicy** [comment]
> 我在node_modules 里看了element plus版本了 都是2.3.4

那我也找不到问题呀啊😂 推荐使用 pnpm 安装了，我本地是没有问题的

**Comment by tlerbao** [comment]
@HalseySpicy 前端真是乱了套了哈哈，npm cnpm pnpm yarn ..... 各家都不一样。难受想哭！

**Comment by HalseySpicy** [comment]
> @HalseySpicy 前端真是乱了套了哈哈，npm cnpm pnpm yarn ..... 各家都不一样。难受想哭！

是的，选择一个就好了，并且一定要有 lock
