### ISSUE TITLE
更新最新版后的小问题

### ISSUE THREAD

**Issue by tlerbao** [HalseySpicy/Geeker-Admin#198]
一、引入App.vue报错
<img width="793" alt="CleanShot 2023-05-12 at 23 04 28@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/43800690-00be-4ce2-82ab-5089c57b5cb2">

二、App.vue内部错误
<img width="831" alt="CleanShot 2023-05-12 at 23 04 56@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/41de7e75-4a70-435f-a3e8-4a65c2d7dcbc">

**Comment by HalseySpicy** [comment]
这是因为 vscode 的 typescript 环境和 TypeScript Vue Plugin (Volar) 组件冲突了，可以禁用 vscode 工作区的 typescript：https://cn.vuejs.org/guide/typescript/overview.html#volar-takeover-mode
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/8eead22f-aaf2-463c-9979-be15c8962bdc)

**Comment by HalseySpicy** [comment]
我也遇到这个问题，刚好解决了

**Comment by tlerbao** [comment]
@HalseySpicy 主要我是webstorm哈哈
