### ISSUE TITLE
频繁出现突然灰屏，导致已打开的标签也变成灰色，不显示任何内容，F5刷新页面后正常

### ISSUE THREAD

**Issue by zhupengfeivip** [HalseySpicy/Geeker-Admin#199]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/30720809/5656d9dd-4fda-494a-80c4-6345585c05b5)

如上图，打开的前两个标签还是正常的。打开角色管理这个标签后，正常使用中，不确定哪个操作后就变成如上图那个灰屏，然后再打开其他标签也是一样的。必须刷新后才恢复正常。不是只有这一个页面，其他页面使用中也会出现同样的问题。

**Comment by HalseySpicy** [comment]
你好，这是 keep-alive 和 transtion 组件导致的这个问题，详情请看这里：https://github.com/HalseySpicy/Geeker-Admin/issues/108
