### ISSUE TITLE
打包后有个问题呀

### ISSUE THREAD

**Issue by baihuijun** [HalseySpicy/Geeker-Admin#2]
登录页的那个背景图是在css里面设置的background-images:url()引入的svg图片 打包后会被打包在asstes/svg/xxx.svg路径下,但是页面引入的背景图路径是在assets/css/xxx.svg,所以部署后背景图出不来   目前有俩种方法 一种是打包后手动把svg目录图片移动到css目录下,另一种是在vite.congfig.ts文件里去掉打包目录分级 把所有资源都打包到同一个目录下 ,  但是感觉这俩方法都不太好 ,我想问下 还有更好的办法吗

**Comment by HalseySpicy** [comment]
目前不会出现这个问题，vite会自动处理图片路径的
![code](https://user-images.githubusercontent.com/51069636/167974200-28b08e5f-c8d9-4563-a0a3-3615b554ba50.png)

**Comment by baihuijun** [comment]
> 目前不会出现这个问题，vite会自动处理图片路径的 ![代码](https://user-images.githubusercontent.com/51069636/167974200-28b08e5f-c8d9-4563-a0a3-3615b554ba50.png)

找到问题了 原来是打包配置了二级目录  然后写了base:'./'  忘写二级目录名了才导致的 ,  感谢作者的回复
