### ISSUE TITLE
大佬，能不能加个主题，菜单模式是混合格式的，一级菜单在上面，一级子菜单在左边

### ISSUE THREAD

**Issue by Amariswade** [HalseySpicy/Geeker-Admin#200]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/25095750/be186169-4996-4a24-8279-5be469eeedc2)

**Comment by HalseySpicy** [comment]
https://github.com/HalseySpicy/Geeker-Admin/issues/125
