### ISSUE TITLE
头部菜单bug,详细请看视频

### ISSUE THREAD

**Issue by zhongyu-y** [HalseySpicy/Geeker-Admin#201]
[https://live.csdn.net/v/297160](url)

**Comment by zhongyu-y** [comment]
当屏幕展示的高度小于菜单展开的高度就会出现以上视频问题

**Comment by HalseySpicy** [comment]
我试了下，是 el-menu 嵌套产生的问题，只有等 element-plus 官方去修复
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/e29892ca-765d-4010-ba23-782c684d4479)

**Comment by HalseySpicy** [comment]
许多使用 element-plus 的开源项目也存在这个问题
