### ISSUE TITLE
当搜索框设置props:clearable后bug

### ISSUE THREAD

**Issue by wangdaxi222** [HalseySpicy/Geeker-Admin#203]
当搜索框设置props:clearable后点击清空数据，这时搜索框数据是空的，但是点搜索还是带defaultValue里面设置的时间

**Comment by HalseySpicy** [comment]
有 defaultValue 就不应该能 clearable 吧，不然逻辑就冲突了。我默认的是有 defaultValue clearable 就为 false
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/47ddcf15-74bf-4f1b-953d-fe7d10864231)

**Comment by wangdaxi222** [comment]
这业务不对吧，刚开始打开表格有个默认时间范围这是一定的，后来想看全部时间范围的数据，不应该清空时间吗？开始和结束时间传空或不传后台就返全部的数据。这样的话如何查看全部时间范围的数据呢？

**Comment by HalseySpicy** [comment]
你可以根据自己的需求改造哟，我目前公司项目需求就是这样的，我个人也认为这个逻辑没有问题

**Comment by HalseySpicy** [comment]
列如几百万条数据或者更多，我肯定只有默认一个日期查询，后端查大数据也会有性能问题吧
