### ISSUE TITLE
iconfont问题，不知道咋解决，问一下大佬

### ISSUE THREAD

**Issue by yangdonbin** [HalseySpicy/Geeker-Admin#205]
目前系统内置了几个iconfont图标，我想加入自己的一些iconfont图标，想把所有图标写在一个iconfont.css文件中，在main.ts中统一引用，但目前的情况是由于有内置的图标，无法用同一个iconfont.css，（也许是我不太懂），求大佬告知

**Comment by HalseySpicy** [comment]
你把阿里图标库账号发我，我可以拉你
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/847fd51b-23ac-4494-ab50-84ff416523a1)

**Comment by yangdonbin** [comment]
好，感谢  我账号  yangdongbin

**Comment by yangdonbin** [comment]
好，看到了
