### ISSUE TITLE
要实现protable的内容加上固定字符串怎么做呢

### ISSUE THREAD

**Issue by wangdaxi222** [HalseySpicy/Geeker-Admin#209]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/84769149/d2692c4f-6b73-48e3-aec2-a370b91fec8b)
要实现protable的内容加上固定字符串要用哪个属性呢？比如后台返25，要在后面加上固定的‘℃’

**Comment by denganjia** [comment]
> ![image](https://user-images.githubusercontent.com/84769149/238871361-d2692c4f-6b73-48e3-aec2-a370b91fec8b.png) 要实现protable的内容加上固定字符串要用哪个属性呢？比如后台返25，要在后面加上固定的‘℃’

可以使用`ColumnProps`里面的`render`，也可以使用插槽
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/46669447/643a6a0f-3fb7-4e78-8aa6-46d2f57c9c04)

**Comment by wangdaxi222** [comment]
好的，多谢
