### ISSUE TITLE
在组件外使用 pinia.js 错误

### ISSUE THREAD

**Issue by ZHUIMEN** [HalseySpicy/Geeker-Admin#21]
错误场景：

 在pinia中使用异步的actions时，并在组件外部使用pinia会报错
![image](https://user-images.githubusercontent.com/30618748/175462161-fbf7f216-2992-4dfa-b757-6e822275a00b.png)

**Comment by HalseySpicy** [comment]
你好，这应该是由pinia组件导致的，我猜想应该是不能在函数或组件外使用pinia，像下面这样使用就没问题
![企业微信截图_20220624123631](https://user-images.githubusercontent.com/51069636/175463239-8f5b4d4b-a6d3-4f00-9f6c-a954603a7c74.png)

**Comment by ZHUIMEN** [comment]
> 你好，这应该是由pinia组件导致的，我猜想应该是不能在函数或组件外使用pinia，像下面这样使用就没问题 ![企业微信截图_20220624123631](https://user-images.githubusercontent.com/51069636/175463239-8f5b4d4b-a6d3-4f00-9f6c-a954603a7c74.png)

你好 正如你截图所示
我也是这么使用的，但是错误依然存在，后来发现 项目中src/api/index.ts 文件使用pinia错误！
![image](https://user-images.githubusercontent.com/30618748/175463959-c6a83b02-8f2d-4af8-b7d2-5b9a71e30c42.png)
![image](https://user-images.githubusercontent.com/30618748/175464067-1e07bfe9-188a-4e00-9f09-3ab487a7aa8b.png)
