### ISSUE TITLE
getTableList里面如何对请求获取到的数据进行处理

### ISSUE THREAD

**Issue by wangdaxi222** [HalseySpicy/Geeker-Admin#210]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/84769149/c6fbd7d7-70b0-4397-b85e-676a7917e7a6)
如图需要对getTempreatureList接口获取到的数据进行处理，但是底下又需要return getTempreatureList(newParams)，这样就造成getTempreatureList这个接口执行了两次。有没有能执行一次就能对数据进行处理的方法呢？

**Comment by denganjia** [comment]
> ![image](https://user-images.githubusercontent.com/84769149/238879414-c6fbd7d7-70b0-4397-b85e-676a7917e7a6.png) 如图需要对getTempreatureList接口获取到的数据进行处理，但是底下又需要return getTempreatureList(newParams)，这样就造成getTempreatureList这个接口执行了两次。有没有能执行一次就能对数据进行处理的方法呢？

不是有个`dataCallback`属性吗，去看下文档

**Comment by wangdaxi222** [comment]
dataCallback只能执行一次，当前页面内有一个类似tab的切换按钮，点一次重新发一次请求，这时候需要重新处理新请求返回的数据，但是dataCallback却不执行了，dataCallback只在进入页面的时候执行一次，怎么才能每次重新发请求都执行一次dataCallback呢？

**Comment by HalseySpicy** [comment]
你确定你试过吗？我每调用一次 proTable.value.getTableList();  dataCallback 函数都会执行一次
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/ff0ff925-9651-4170-870d-d223d3611768)
