### ISSUE TITLE
想给菜单添加新的图标，在哪里添加呢

### ISSUE THREAD

**Issue by enilu** [HalseySpicy/Geeker-Admin#211]
菜单配置中有icon配置项，请问这一项对应的是哪里呢，如果我像添加一个新的菜单图标，如何添加呢

**Comment by HalseySpicy** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/f27a43d1-7eb6-4f85-9aad-f5a8affcf608)

**Comment by HalseySpicy** [comment]
https://admin.spicyboy.cn/#/assembly/selectIcon

**Comment by Howie7793** [comment]
请问下我想要添加我们ui设计的icon，在iconfont中，我应该怎么使用到菜单栏中呢

**Comment by Howie7793** [comment]
> ![image](https://private-user-images.githubusercontent.com/51069636/239129150-f27a43d1-7eb6-4f85-9aad-f5a8affcf608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzgyNTgsIm5iZiI6MTcwODY3Nzk1OCwicGF0aCI6Ii81MTA2OTYzNi8yMzkxMjkxNTAtZjI3YTQzZDEtN2ViNi00Zjg1LTlhYWQtZjVhOGFmZmNmNjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA4NDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZWYzMWE1YzQwMTg0ZTE3ZjBhYzM0ZGJiNjM4MmU3NmU1MmVmNmJhNzNjNGQyZDIyN2FkMjI2YTlkMTBhNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W7hUWJfxoCxIbD8Me0ZBZacWPGmn-r8Dg9kkc6MzFlg)

请问下我想要添加我们ui设计的icon，在iconfont中，我应该怎么使用到菜单栏中呢
