### ISSUE TITLE
设置搜索后，表格显示有问题

### ISSUE THREAD

**Issue by wangdaxi222** [HalseySpicy/Geeker-Admin#212]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/84769149/4bc10503-d2ea-4cfc-ad73-a94e668e43fa)
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/84769149/0690a7bf-c70d-4376-ad5a-27e7a1ae0f71)

这样设备名称显示不出来
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/84769149/78dc6b03-7ea3-4eb9-b9b5-b7f3d4b67e9b)
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/84769149/938d5b5f-3227-482d-8b4c-79d33cefec08)
把他注释掉后就能显示出来了，但这样就没有搜索了。有搜索时搜索正常可用。请问这是哪里出问题了？

**Comment by HalseySpicy** [comment]
你认真看下文档嘛
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/00810576-c7c4-4c46-a1d2-3c6b2b1957bf)

**Comment by wangdaxi222** [comment]
哦 可以了

**Comment by HalseySpicy** [comment]
可以直接加群讨论

**Comment by wangdaxi222** [comment]
请问群号在哪呢？我找了半天没找到

**Comment by denganjia** [comment]
> 请问群号在哪呢？我找了半天没找到
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/46669447/c3f124b1-748b-4efd-a55e-95d08ae2f87b)
