### ISSUE TITLE
TS2307: Cannot find module '@/views/login/index.vue' or its corresponding type declarations.

### ISSUE THREAD

**Issue by yushilong** [HalseySpicy/Geeker-Admin#213]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/5087094/87094c7a-7d10-458e-b779-754a5a61f32f)

**Comment by yushilong** [comment]
项目可以正常运行起来，就是有这种warnning

**Comment by HalseySpicy** [comment]
你可以看看是不是这个问题：https://github.com/HalseySpicy/Geeker-Admin/issues/198
