### ISSUE TITLE
为什么当前页面没引用的scss文件，却能在当前页生效

### ISSUE THREAD

**Issue by wangdaxi222** [HalseySpicy/Geeker-Admin#214]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/84769149/1c6fe8bf-27ea-477b-a5d8-eaf3b8ae2cdc)
如图，我只引用了一个index.scss，但却有别的scss样式却能在本页生效。这是因为什么，如何修改让他在本页不生效

**Comment by HalseySpicy** [comment]
我也看不到你咋写的呀😂

**Comment by wangdaxi222** [comment]
不用看到啊，就是我只引用了index.scss,但是dataList.scss的样式在本页生效了

**Comment by HalseySpicy** [comment]
……我咋知道你怎么写的😂

**Comment by wangdaxi222** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/84769149/bc22654c-dff3-4eeb-a1b7-5dab663410c3)
你自己框架不知道怎么写的吗？问题不是我怎么写的，是你怎么写的？我用的你的框架。看到图片了吧，只引入了一个scss，但是另一个没引入的scss却能在本页生效。这很难理解吗？
