### ISSUE TITLE
分页点击时参数为空

### ISSUE THREAD

**Issue by dxl727754275** [HalseySpicy/Geeker-Admin#217]
如图
<img width="894" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/40659245/71d383bf-b81b-4e12-9afc-a2cca3ab4bf5">
首次刷新页面pagesize存在，但是在点第二页时候，则不存在了，请求后端时候也没携带该参数
<img width="197" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/40659245/d3922e58-6069-47c1-a2a8-b7e14eddcb37">
导致我无法翻页，没有改动分页相关的代码
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/40659245/d128c10c-27e7-48f8-a676-75575e2bdef3)
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/40659245/abdfaaf4-ca99-485d-ba58-b1cb531d5171)
我在requestapi处配置的console。log就不见了参数，请问我该怎么办，感谢

**Comment by HalseySpicy** [comment]
后端返回数据截个图

**Comment by dxl727754275** [comment]
> 后端返回数据截个图

<img width="620" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/40659245/0705b366-e797-4a3c-8174-d5e23c4ac3aa">
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/40659245/9276820f-1f37-4462-8639-616864930ea4)
ho后端逻辑因为=0所以为10

**Comment by dxl727754275** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/40659245/bf06cb9e-dc72-4764-9188-dfe58480bb57)

**Comment by HalseySpicy** [comment]
要么后端返回 pageNum、pageSize。或者这样改也行：
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/c0ad07f3-4c23-4a41-92ce-d07d21b217e6)
