### ISSUE TITLE
树形表格数据源结构若返回hasChildren，则树形样式出不来

### ISSUE THREAD

**Issue by maguoliang888** [HalseySpicy/Geeker-Admin#218]
如题
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/67767897/448c68fe-750f-46a4-98a5-987342469adf)

![image](https://github.com/HalseySpicy/Geeker-Admin/assets/67767897/04e7af74-38a9-4c69-bf07-fcb162582583)

**Comment by HalseySpicy** [comment]
看文档， hasChildren 字段是用来做懒加载的
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/1a88a273-6f1e-40b9-bde3-7573b6ec75a4)

**Comment by maguoliang888** [comment]
ok明白了。多谢
