### ISSUE TITLE
请问有没有合并单元格的方法

### ISSUE THREAD

**Issue by txb1003** [HalseySpicy/Geeker-Admin#220]

**Comment by denganjia** [comment]
合并单元格是ElTable 的功能：https://element-plus.org/zh-CN/component/table.html#%E5%90%88%E5%B9%B6%E8%A1%8C%E6%88%96%E5%88%97。
可以按照官方文档将属性传递给ProTable，内部会透传至el-table

**Comment by txb1003** [comment]
好的，了解了
