### ISSUE TITLE
布局排版

### ISSUE THREAD

**Issue by tzwhyqq** [HalseySpicy/Geeker-Admin#221]
大佬能加下，类似vben admin 那些一些配置，如布局左侧菜单，还是上下菜单。 颜色，等配置自定义选型吗

**Comment by HalseySpicy** [comment]
项目中有主题布局设置：
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/ea9417b4-5053-4a4f-8898-897cd3f445ad)
