### ISSUE TITLE
如何只给ProTable加上水印

### ISSUE THREAD

**Issue by xzusoft001** [HalseySpicy/Geeker-Admin#229]
如题如何只给portable加上水印。自定义指令中的水印会被表格遮盖住

**Comment by HalseySpicy** [comment]
#232

**Comment by lianglingbo** [comment]
同问

**Comment by lianglingbo** [comment]
.el-table ,.el-table tr {
    background-color: transparent !important;
  }

**Comment by HalseySpicy** [comment]
https://element-plus.org/zh-CN/component/watermark.html
