### ISSUE TITLE
大佬能不能开发一下数据库如果存的图片是key，然后环境设置，填写图片前缀域名

### ISSUE THREAD

**Issue by cchh2277** [HalseySpicy/Geeker-Admin#230]
大佬能不能开发一下数据库如果存的图片是key，然后环境设置，填写图片前缀域名。
变量为空：直接获取数据库图片存的是完整的地址，
如果不为空，就拼接~

**Comment by Kassell** [comment]
> 

能描述的具体一点？在什么地方使用

**Comment by haobarry** [comment]
自己写个hooks

**Comment by cchh2277** [comment]
duck不必回复。




ok
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HalseySpicy/Geeker-Admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 下午5:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HalseySpicy/Geeker-Admin] 大佬能不能开发一下数据库如果存的图片是key，然后环境设置，填写图片前缀域名 (Issue #230)





 
自己写个hooks

**Comment by HalseySpicy** [comment]
根据需求，自行添加即可
