### ISSUE TITLE
大佬，能不能再treeTable组件上实现以下增删改的功能呀，目前只是查询渲染

### ISSUE THREAD

**Issue by Amariswade** [HalseySpicy/Geeker-Admin#231]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/25095750/7969dc99-9fad-409f-9349-4fbdb6a5de5b)

**Comment by HalseySpicy** [comment]
我这里部门列表只是筛选作用，况且这是你自己需求吧

**Comment by HalseySpicy** [comment]
> ![image](https://user-images.githubusercontent.com/25095750/244854042-7969dc99-9fad-409f-9349-4fbdb6a5de5b.png)

部门列表应该是一个模块去管理的，

**Comment by Amariswade** [comment]
把部门列表看做是一个分类，分类下有数据，在一个页面既可以对分类做管理，也可以对分类下的数据做管理，这样子是不是方便一点？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HalseySpicy/Geeker-Admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月11日(星期天) 晚上9:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HalseySpicy/Geeker-Admin] 大佬，能不能再treeTable组件上实现以下增删改的功能呀，目前只是查询渲染 (Issue #231)





  

  
部门列表应该是一个模块去管理的，
