### ISSUE TITLE
后端选手卑微请教水印指令怎么实现全屏水印

### ISSUE THREAD

**Issue by heycm** [HalseySpicy/Geeker-Admin#232]
水印指令挂载app.vue会被盖在底层

**Comment by lianglingbo** [comment]
.el-table ,.el-table tr {
    background-color: transparent !important;
  }

**Comment by lianglingbo** [comment]
背景设成透明

**Comment by HalseySpicy** [comment]
https://element-plus.org/zh-CN/component/watermark.html
