### ISSUE TITLE
个别时候登录系统后404

### ISSUE THREAD

**Issue by tlerbao** [HalseySpicy/Geeker-Admin#233]
在个别时候登录系统后显示404，刷新一下即可正确显示系统首页，很奇怪是什么原因呢

不是每次都出现

<img width="1051" alt="CleanShot 2023-06-11 at 14 05 26@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/d9d5f5eb-7d93-4365-92db-e69f9dd23679">

**Comment by HalseySpicy** [comment]
老哥，无法复现

**Comment by tlerbao** [comment]
> 老哥，无法复现

那么下次出现的时候我应该做点什么哈哈哈

**Comment by HalseySpicy** [comment]
> > 老哥，无法复现
> 
> 那么下次出现的时候我应该做点什么哈哈哈

看看有没有报错，然后在404页面的时候把 vue devtools 的路由表截图看看，

**Comment by jianhao2010303** [comment]
+1，也会有同样现象。

**Comment by mrhulhw123456** [comment]
> 老哥，无法复现
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/130449286/7905d3c5-e416-408b-90ed-5ba36afd5fd1)
复现了，发现了规律;
正常登录之后跳到首页，然后随意执行一些代码，比如console.log，页面会更新，此时退出重新登陆就会大概率复现
我是在LoginForm.vue组件里打印了个返回值

**Comment by tlerbao** [comment]
@HalseySpicy 看来不止我一人有这个问题

**Comment by HalseySpicy** [comment]
> > 老哥，无法复现
> > ![image](https://user-images.githubusercontent.com/130449286/248732517-7905d3c5-e416-408b-90ed-5ba36afd5fd1.png)
> > 复现了，发现了规律;
> > 正常登录之后跳到首页，然后随意执行一些代码，比如console.log，页面会更新，此时退出重新登陆就会大概率复现
> > 我是在LoginForm.vue组件里打印了个返回值

意思是只有本地改了代码才会出现嘛，生产环境没有？

**Comment by mrhulhw123456** [comment]
> 

只是本地运行发现此问题，暂未部署到生产，还在熟悉项目框架，新的业务线准备用这个框架。

**Comment by mrhulhw123456** [comment]
> > > 老哥，无法复现
> > > ![image](https://user-images.githubusercontent.com/130449286/248732517-7905d3c5-e416-408b-90ed-5ba36afd5fd1.png)
> > > 复现了，发现了规律;
> > > 正常登录之后跳到首页，然后随意执行一些代码，比如console.log，页面会更新，此时退出重新登陆就会大概率复现
> > > 我是在LoginForm.vue组件里打印了个返回值
> 
> 意思是只有本地改了代码才会出现嘛，生产环境没有？

只是本地运行发现此问题，暂未部署到生产，还在熟悉项目框架，新的业务线准备用这个框架。

**Comment by tlerbao** [comment]
@HalseySpicy 我按照刚才那个小哥操作了一下，我擦 果然

1. 随便改下代码
2. 浏览器自动热更新然后退出
3. 再登陆就404，刷新后正常

https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/f5f87cea-1f71-4470-933d-95337e84e7e4

**Comment by KunlunLu** [comment]
有解决吗

**Comment by Alanrah** [comment]
+1

**Comment by HalseySpicy** [comment]
我把 vite 升级到 4.4.2 版本，没有出现这个问题，大家可以试试

**Comment by HalseySpicy** [comment]
已更新

**Comment by mzcc666GtHb** [comment]
+1

**Comment by loyipsing** [comment]
同样的问题已经解决(我的是本地静态路由)，登出的时候，会返回到login页面，此时路由守卫会调用resetRouter清空路由表，但是authStore里面的authMenuList不为空，登陆成功后再次路由守卫就没有重新初始化路由表，就出问题了。

目前还是初学前端，原理不对请见谅。

目前我的解决办法是：

`在 authStore 添加一个action函数<清空authMenuList和authButtonList>给resetRouter调用` 

> 已更新

@HalseySpicy

**Comment by LBC000** [comment]
+1
