### ISSUE TITLE
中英文切换的

### ISSUE THREAD

**Issue by chenhaijia** [HalseySpicy/Geeker-Admin#236]
`const columns: Partial<ColumnProps>[] = [
	{
		prop: "accountType",
		label: t("revenue.customerType"),
		sortable: "custom",
		minWidth: 100
	},
	{ prop: "useAddr", label: t("revenue.waterUsageAddress"), sortable: "custom", minWidth: 150 },
	{ prop: "operation", label: t("public.operate"), sortable: "custom", width: "110", fixed: "right" }
];`

`<ProTable
stripe
ref="proTable"
:columns="columns"
:toolButton="false"
:requestApi="getProfileAccountList"
:initParam="initParam"
>

</ProTable>`

**Comment by chenhaijia** [comment]
i18n 国际化 第一次页面加载不出来英文 需页面关掉 重新打开 才能加载出来

**Comment by HalseySpicy** [comment]
ProTable 不支持动态改变 columns， 你改中英文之后 reaload 下页面

**Comment by chenhaijia** [comment]
回复速度点个赞 吓我一跳

**Comment by HalseySpicy** [comment]
> 回复速度点个赞 吓我一跳

点个 star
