### ISSUE TITLE
请问支持横向一级菜单 侧边揽为2 3..菜单嘛

### ISSUE THREAD

**Issue by lovesL** [HalseySpicy/Geeker-Admin#237]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/27960630/1cc99390-effb-43cd-b184-ba2b10deabeb)
可参考若依

**Comment by lovesL** [comment]
> #125

没有相关文档更新啊  只看到完成了

**Comment by HalseySpicy** [comment]
意思是还没写，别人已经提了🤣
