### ISSUE TITLE
webstorm的类型错误，我测试了一下，小哥看看

### ISSUE THREAD

**Issue by tlerbao** [HalseySpicy/Geeker-Admin#241]
### 先如图，就这种错误

<img width="1442" alt="CleanShot 2023-06-20 at 23 03 54@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/547e62f6-4ae3-4f49-b376-edc67078418f">

### 看视频，经过我测试去掉配置项的render和search的 props，警告就没了，不知道为何哈哈，强迫症很难受

https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/09380bac-4eac-401b-a2de-3ab58e82ab43

### 另外 button的icon传图标component也是报错

<img width="1329" alt="CleanShot 2023-06-20 at 23 06 21@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/9dcf4c95-e864-4ee8-99b6-00bd78175f98">

**Comment by HalseySpicy** [comment]
我也不知道，没用过 webstorm 🤣

**Comment by tlerbao** [comment]
> 我也不知道，没用过 webstorm 🤣

你用吧，用完就回不去了，就吃点内存哈哈哈
