### ISSUE TITLE
开发环境跨域代理，支持配置多个, 如何配置

### ISSUE THREAD

**Issue by mrhulhw123456** [HalseySpicy/Geeker-Admin#244]
# 开发环境跨域代理，支持配置多个
VITE_PROXY = [["/api","https://mock.mengxuegu.com/mock/629d727e6163854a32e8307e"]]

这是系统自带的 ,我想保留
然后我自己弄了一个 https://www.fastmock.site/mock/56a16084d09ea8c307f70918763dd25a
我想在本地2个都可以请求通过,怎么做

**Comment by mrhulhw123456** [comment]
# 开发环境接口地址
VITE_API_URL = /api

# 开发环境跨域代理，支持配置多个
# VITE_PROXY = [["/api","https://mock.mengxuegu.com/mock/629d727e6163854a32e8307e"]]
# VITE_PROXY = [["/api","https://www.fastmock.site/mock/f81e8333c1a9276214bcdbc170d9e0a0"]]
VITE_PROXY = [["/api","https://mock.mengxuegu.com/mock/629d727e6163854a32e8307e"],["/api","https://www.fastmock.site/mock/f81e8333c1a9276214bcdbc170d9e0a0"]]

/api要一样吗,大佬求教

**Comment by HalseySpicy** [comment]
![bef63f453a597df150b9fcd50713288](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/a2861179-2e6e-4709-b9d7-23d2d488a3e2)

**Comment by mrhulhw123456** [comment]
大神V5

**Comment by tcmdxc430** [comment]
然后呢大哥 新定义的http1在哪调用啊

**Comment by tcmdxc430** [comment]
大哥这样写编译不过去啊Property 'get' does not exist
