### ISSUE TITLE
定义带参数的路由的正确姿势是怎样的？

### ISSUE THREAD

**Issue by tlerbao** [HalseySpicy/Geeker-Admin#245]
我定义了一个路由菜单 /crm/material/:type ，直接访问 url中也有 :type ，所以我把他隐藏了，然后创建了三个不同参数的路由菜单，但是我发现只有最后创建的一个可以访问

**又菜的抠脚了，请问正确姿势是怎样的？或者说我这种N个菜单其实path是一样，但是参数不一样的情况应该怎么做呢**
<img width="859" alt="CleanShot 2023-06-26 at 22 27 06@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/4b814e3d-2bb4-48ba-bba6-89f3af2e248a">

<img width="319" alt="CleanShot 2023-06-26 at 22 26 45@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/d4a5b589-1778-43e3-a9c7-df106a762d08">

![CleanShot 2023-06-26 at 22 31 08@2x](https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/deead6f1-9dbc-4400-ad22-783a604dd387)

**Comment by tlerbao** [comment]
**然后 /xxx/xxx?type=xxx 形式又不行，直接404**


<img width="589" alt="CleanShot 2023-06-26 at 22 46 02@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/f5798676-a649-4c84-9ae3-7d8865793767">


<img width="1353" alt="CleanShot 2023-06-26 at 22 44 33@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/d1cba107-898e-44c4-bfbf-2defae8a65b5">

**Comment by HalseySpicy** [comment]
https://docs.spicyboy.cn/guide/router.html

**Comment by tlerbao** [comment]
@HalseySpicy 
你可能没太理解我的意思小老板

### 首先
如果我新建一个隐藏的 /xxx/:type 形式的路由（菜单），那么我在页面中的各种链接或按钮 /xxx/article, /xxx/video,/xxx/images 都可以正常路由过去，因为菜单里只有一个  /xxx/:type  的路由 （菜单）

但是我想把 /xxx/article, /xxx/video,/xxx/images三个全弄菜单离去也就是三个菜单 而 article和video和image我相依:type路由参数的形式获取来区分数据列表的不同展示。但是肯定不行

### 其次
其实我完全不用管:type形式，直接新建三个菜单/xxx/article, /xxx/video,/xxx/images，然后用解析路由最后一位的方法来区分，但是又好像很傻比

### 然后

新建 /material?type=article 这种形式路由菜单访问会直接404，不能支持 ?type=article 的形式吗？

**Comment by HalseySpicy** [comment]
直接私信我吧
