### ISSUE TITLE
两个样式问题

### ISSUE THREAD

**Issue by tlerbao** [HalseySpicy/Geeker-Admin#246]
### 当给el-image增加了:preview-src-list="[scope.row.cover_pic]" 时，点击预览如下效果直接崩坏

<img width="1412" alt="CleanShot 2023-06-27 at 15 19 52@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/a987f629-12cd-4cbc-88ba-e4f257b7c22c">

### 二、空表格这里的样式也不太对

![CleanShot 2023-06-27 at 15 20 28@2x](https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/6f6519bf-c687-48bd-8535-2c796a822171)

**Comment by HalseySpicy** [comment]
看文档啊，老哥
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/6f4dfa18-170c-483b-b0f1-55715eeb12b9)

**Comment by HalseySpicy** [comment]
> ### 当给el-image增加了:preview-src-list="[scope.row.cover_pic]" 时，点击预览如下效果直接崩坏
> <img alt="CleanShot 2023-06-27 at 15 19 52@2x" width="1412" src="https://user-images.githubusercontent.com/20442232/249067840-a987f629-12cd-4cbc-88ba-e4f257b7c22c.png">
> ### 二、空表格这里的样式也不太对
> ![CleanShot 2023-06-27 at 15 20 28@2x](https://user-images.githubusercontent.com/20442232/249068050-6f6519bf-c687-48bd-8535-2c796a822171.png)

关于第二个问题。我的是正常的

**Comment by tlerbao** [comment]
@HalseySpicy 
好的好的。
哈哈 谁会想到在常见问题里呢哈哈，
