### ISSUE TITLE
超级Table可以支持列的拖拽嘛？

### ISSUE THREAD

**Issue by a13294592142** [HalseySpicy/Geeker-Admin#247]

**Comment by HalseySpicy** [comment]
可以做，但是多级表头有问题，去掉了

**Comment by a13294592142** [comment]
感觉多级表头需求还是比较少的 拖拽好像更实用&nbsp; 哈哈
&nbsp;


王三岁°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月27日(星期二) 下午5:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HalseySpicy/Geeker-Admin] 超级Table可以支持列的拖拽嘛？ (Issue #247)





 
可以做，但是多级表头有问题，去掉了

**Comment by HalseySpicy** [comment]
自己实现也很简单，用 SortableJS

**Comment by a13294592142** [comment]
好的，谢谢大佬，愿项目越来越好，越来越火
&nbsp;


王三岁°
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月27日(星期二) 晚上6:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HalseySpicy/Geeker-Admin] 超级Table可以支持列的拖拽嘛？ (Issue #247)





 
自己实现也很简单，用 SortableJS

**Comment by HalseySpicy** [comment]
> 好的，谢谢大佬，愿项目越来越好，越来越火 &nbsp; 王三岁° ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年6月27日(星期二) 晚上6:07 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [HalseySpicy/Geeker-Admin] 超级Table可以支持列的拖拽嘛？ (Issue #247) 自己实现也很简单，用 SortableJS — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

后期有空我完善一下，多级表头我就去掉拖拽
