### ISSUE TITLE
keepalive,进入数据大屏页面返回后不缓存

### ISSUE THREAD

**Issue by xqs95** [HalseySpicy/Geeker-Admin#249]
使用keepalive对列表页进行缓存，其它页面返回缓存，进入数据大屏页面返回不缓存

**Comment by HalseySpicy** [comment]
我看了这个问题，数据大屏不属于 layout 下面的页面，要让数据大屏缓存的话，目前改动很大，有需求的话请自行改造。
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/260b5e04-d5c2-4217-884f-ce8802d0c93a)
