### ISSUE TITLE
template下不能有多个html标签，不然切换菜单空白

### ISSUE THREAD

**Issue by pangpangma** [HalseySpicy/Geeker-Admin#250]
我创建一个菜单页面，然后template下写了多个div，切换到这个新建的菜单之后再切到其他页面不渲染，页面为空白。删除多个div只保留一个就ok了。问题解决，但是不知道所以

**Comment by HalseySpicy** [comment]
虽然 vue3 支持多个根节点，但是 transition 不支持

**Comment by HalseySpicy** [comment]
#108
