### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by xu-Aurora** [HalseySpicy/Geeker-Admin#26]
感觉应该把 el-table自带的属性也可以透传过去。否则直接使用pro-table 之后 要对table的属性进行一些配置，得改动 column的接口类型

**Comment by denganjia** [comment]
> 感觉应该把 el-table自带的属性也可以透传过去。否则直接使用pro-table 之后 要对table的属性进行一些配置，得改动 column的接口类型

现在ProTable已经重构的差不多了，觉得会让你大吃一惊。敬请期待新版本的发布
