### ISSUE TITLE
随便更改页面热更新后，点击其他菜单路由全部空白

### ISSUE THREAD

**Issue by tlerbao** [HalseySpicy/Geeker-Admin#261]
如视频，随便改一个页面的代码，热更新后，点击其他菜单路由都空白，刷新后正常

https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/8eb8b7e4-0e90-4962-b90e-608f5528facd

**Comment by HalseySpicy** [comment]
不是说过这个问题吗？https://github.com/HalseySpicy/Geeker-Admin/issues/108

**Comment by HalseySpicy** [comment]
#108
