### ISSUE TITLE
表格的列enum回显问题请教

### ISSUE THREAD

**Issue by tlerbao** [HalseySpicy/Geeker-Admin#262]
本来如下图这样就可以直接数据回显，但是因为表格里的group_id返回的是 number 类型，但是getDictDataApi返回的对应value是string类型，所以匹配不上，

有经验的小哥 @HalseySpicy 这个怎么处理一下比较好？

![CleanShot 2023-07-12 at 16 23 04@2x](https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/1c86ef72-081c-423d-992f-2b2eb9620b4f)

**Comment by HalseySpicy** [comment]
默认是 ===，你改为 == 就好了，按道理的话，你应该叫后端改啊🤣
![1689154396074](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/b95d82cf-2c93-4df3-adfc-af8cb804908a)

**Comment by tlerbao** [comment]
@HalseySpicy 后端也是我哈哈，主要是dict字典的value肯定是varchar类型，同时满足 有时值是 number 有时是string，而不同数据表的具体值也有可能是 number 和string哈哈，当然string时就不用处理，就会自动匹配了，number时就要搞一下。
