### ISSUE TITLE
登录系统后404

### ISSUE THREAD

**Issue by tshengjun** [HalseySpicy/Geeker-Admin#263]
#233 vite 升级到 4.4.3 之后，还是会出现 404 ，操作是一样的，操作速度快一点就会重现这种问题。
![1689226198609](https://github.com/HalseySpicy/Geeker-Admin/assets/29391642/4cdb5cda-937c-4368-a1ac-4b98d2a4d188)

**Comment by HalseySpicy** [comment]
我操作了很多次，无法复现，我使用的 vite 4.4.2 版本，确保你已经把 node_modules 已经删除，重新使用 pnpm 安装了，如果还是出现，可以录个视频哟

**Comment by tshengjun** [comment]
node_modules 删了，出现概率很小，后续再出现我录个视频
