### ISSUE TITLE
内置校验繁多，windows电脑开发容易检验报错，建议指南上说明各种校验的开启和关闭

### ISSUE THREAD

**Issue by LeftProgrammer** [HalseySpicy/Geeker-Admin#264]

**Comment by denganjia** [comment]
1. 如果不想使用校验工具，请直接移除eslint和prettier相关依赖

**Comment by denganjia** [comment]
> _No description provided._
 如果不想使用校验工具，请直接移除eslint和prettier相关依赖，而且[文档](https://docs.spicyboy.cn/guide/standard.html)里也详细描述了各个配置的功能
