### ISSUE TITLE
项目打包偏慢

### ISSUE THREAD

**Issue by LeftProgrammer** [HalseySpicy/Geeker-Admin#267]

**Comment by denganjia** [comment]
> _No description provided._

因为项目全量引入了ElementPlus，再加上一些第三方依赖，随着项目越来越大，页面和功能越来越多，打包偏慢是很正常的事情。
在我的电脑（i5-10400 CPU @ 2.90GHz +  16GB）上从执行打包命令到打包完成总共耗时约80秒。
如果你打包比这还慢，真心建议换个配置好的电脑
