### ISSUE TITLE
不在列表显示的字段希望可以通过列设置进行控制是否显示

### ISSUE THREAD

**Issue by zscgxs** [HalseySpicy/Geeker-Admin#269]
不在列表显示的字段希望可以通过列设置进行控制是否显示，希望在proTable使用时可以控制显示隐藏的字段，这样后面可以根据账号设置列表显示字段存到数据库中
<img width="1440" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/52776819/c34c825e-70ae-4d57-81c5-d87e974c4129">

**Comment by HalseySpicy** [comment]
我这没有后台数据库，自行改造即可
