### ISSUE TITLE
超级表格下的使用Protable模块的表格多选bug

### ISSUE THREAD

**Issue by LeftProgrammer** [HalseySpicy/Geeker-Admin#270]
默认未选中数据时删除按钮置灰， 勾选数据后变亮。 表格勾选数据后点击分页，在点分页回来，表格勾选状态被清除，但勾选数据还存在，导致页面看似没有勾选任何数据，但删除按钮还是亮的。实际进行请求时，是存在勾选数据的

**Comment by HalseySpicy** [comment]
mock 数据。每次数据 id 都不一样

**Comment by HalseySpicy** [comment]
真实数据没有问题的
