### ISSUE TITLE
[Style] el-popup-parent--hidden 会携带 width: calc(100% - 8px) 样式 

### ISSUE THREAD

**Issue by qq1036828060** [HalseySpicy/Geeker-Admin#276]
我看到大佬在ele-plus 下面提交了Issues，但是Issues已经被关闭，里面也没有具体解决这个问题方法，想问下大佬解决这个问题了吗？

**Comment by HalseySpicy** [comment]
后面 element-plus更新之后，就没遇到了

**Comment by qq1036828060** [comment]
在大佬演示页面不还是有这个问题吗？还是说要更新一下ele-plus版本？
