### ISSUE TITLE
ProTable Formatter 不能够正确执行

### ISSUE THREAD

**Issue by thinkhuang10** [HalseySpicy/Geeker-Admin#279]
您好，ProTable表格中有一列为日期，想格式化日期，使用Formatter，不能够正确触发。
![1691313120513](https://github.com/HalseySpicy/Geeker-Admin/assets/28584326/7cd6a4e7-c948-405c-a4aa-3efcf5c457d0)

**Comment by HalseySpicy** [comment]
请使用 render
