### ISSUE TITLE
详情界面可以只在当前界面打开子界面

### ISSUE THREAD

**Issue by xzghting** [HalseySpicy/Geeker-Admin#284]
1.在界面中，进入详情界面时，只在当前界面打开，不新开tab详情页。
2.如果打开详情，能只开一个吗？
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/13431205/ff4918f3-2c09-47ad-abc3-b5f0a4a89de3)

**Comment by HalseySpicy** [comment]
url 地址 + 参数一致，只会打开一个
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/3be0379f-8595-486a-934d-086c3d8db019)

**Comment by xzghting** [comment]
> url地址+参数一致，只需打开一个 ![图像](https://user-images.githubusercontent.com/51069636/259276199-3be0379f-8595-486a-934d-086c3d8db019.png)

可以在当前界面打开吗，不新开子界面

**Comment by HalseySpicy** [comment]
可以呀，使用 v-show 控制组件显示呗

**Comment by xzghting** [comment]
> 可以呀，使用 v-show 控制组件显示呗

之前我就是这样做的 -  -
