### ISSUE TITLE
drawer展开的一瞬间底部出现了横向滚动条导致屏幕闪一下

### ISSUE THREAD

**Issue by xkfe** [HalseySpicy/Geeker-Admin#285]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/129662190/bbe4e2b9-def2-4d33-ae0a-5de5054e1280)

**Comment by HalseySpicy** [comment]
这个问题是 gif 图片影响的，头像换张 png 图片就没问题了，具体原因我也不清楚，我也是 debug 了一天才找到原因的
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/476ecdbb-eb45-405a-b728-ffeeadab1c6e)

**Comment by tlerbao** [comment]
@HalseySpicy 这你都能debug到我擦，牛逼

**Comment by HalseySpicy** [comment]
> @HalseySpicy 这你都能debug到我擦，牛逼

debug 小能手，还有很多意想不到的问题 🤣

**Comment by xkfe** [comment]
厉害了。我以为是布局样式问题，居然是头像gif导致的·😂
