### ISSUE TITLE
defaultValue如何根据接口返回值动态设置？

### ISSUE THREAD

**Issue by xkfe** [HalseySpicy/Geeker-Admin#286]
1、我的下拉搜索框内容需要根据接口获取，数据返回后，这里没有响应式更改。应该怎么写呀？😂
2、关于`enum`如果返回的数据是对象，如何拿到里面的`list`呀？
```js
{
  pageNum:1,
  pageSize:10,
  list: [...]，
...
}
```
> **最后，作者大神方便建一个交流群吗？大家遇到问题可以相互交流帮助**

![image](https://github.com/HalseySpicy/Geeker-Admin/assets/129662190/f8891aa1-6c23-4490-aec4-1f94c272de64)

**Comment by xkfe** [comment]
@HalseySpicy 求救🆘😭

**Comment by HalseySpicy** [comment]
更新我添加个示例

**Comment by xkfe** [comment]
@HalseySpicy 更新示例了吗大佬，我现在 Column里面的isShow也不能响应式。不知道怎么写

<img width="480" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/129662190/ce526466-8390-4cf8-bc53-7d22c21368d0">

**Comment by xkfe** [comment]
@HalseySpicy 这样也不行😭

![image](https://github.com/HalseySpicy/Geeker-Admin/assets/129662190/0d3c5d4b-3933-4777-a961-ee28e2dd3b01)

**Comment by HalseySpicy** [comment]
首先设置  :request-auto="false"，然后 enum 数据请求回来之后这样写，就可以不用在 column 中设置 defaultValue 了：
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/8ab42970-65ef-4ea2-b3f6-b525cf83f162)

**Comment by xkfe** [comment]
@HalseySpicy 问题一我是这么解决的，已经处理完毕了。问题二：表格动态列切换不知道如何响应式？如失败原因我想在点击“失败”的tab栏时显示出来应该如何做呢？

**Comment by HalseySpicy** [comment]
问题二我没理解到

**Comment by xkfe** [comment]
@HalseySpicy  表格动态列

![image](https://github.com/HalseySpicy/Geeker-Admin/assets/129662190/dc0a73c9-2c99-48d1-854a-2d6a58089f77)

**Comment by HalseySpicy** [comment]
不支持，需要自己改造
