### ISSUE TITLE
头部导航，二级菜单无图标时，文字不对齐

### ISSUE THREAD

**Issue by iHTCboy** [HalseySpicy/Geeker-Admin#287]
无图标时，文字不对齐：
<img width="540" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/11418363/a5f047a6-5d39-4e77-963f-96707f264835">

有图标时，文字对齐：
<img width="437" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/11418363/d0a0e060-e57c-4ca6-abd2-33f531cffbf0">

**Comment by HalseySpicy** [comment]
已修复：https://github.com/HalseySpicy/Geeker-Admin/commit/c6107557ffc0445e9bf3a34229d2a830a5040d67
