### ISSUE TITLE
tab栏切换的时候有时候会不触发请求，没设置keepalive ，不是每次都有的，好像是打开两个放一段时间才有可能出现

### ISSUE THREAD

**Issue by zscgxs** [HalseySpicy/Geeker-Admin#290]
https://github.com/HalseySpicy/Geeker-Admin/assets/52776819/5e4c3f46-b857-4e2c-919c-7bdc550c56aa

**Comment by ping-xiong** [comment]
今天我也遇到了，我看这个解决方法解决了： #108

**Comment by HalseySpicy** [comment]
#108
