### ISSUE TITLE
选择表格项之后是否能显示选中多少个？

### ISSUE THREAD

**Issue by huguodong** [HalseySpicy/Geeker-Admin#299]
类似这种
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/12368323/6aae88a2-fdec-461c-a335-dbc702376b28)
或者这种
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/12368323/839f5609-d83c-4ed3-8d35-ffc52456fa77)

**Comment by tlerbao** [comment]
这个自己count一下就行了吧

**Comment by HalseySpicy** [comment]
文档不写了吗
proTable.value,selectedList.length
