### ISSUE TITLE
配置使用本地mock数据

### ISSUE THREAD

**Issue by zhfling** [HalseySpicy/Geeker-Admin#301]
https://mock.mengxuegu.com/ 不能访问，无法登陆，怎么样切换mock平台，或配置使用本地mock数据？

**Comment by HalseySpicy** [comment]
这两个都试试，正常两个都行
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/3b0421a4-56dd-40d1-9ffe-a3b53df44b7d)
