### ISSUE TITLE
这个TS问题是什么原因导致的，演示文件也有这个问题

### ISSUE THREAD

**Issue by tlerbao** [HalseySpicy/Geeker-Admin#302]
下面是官方useTreeFilter的代码，我增加了高亮的部分，为何这里会报“未解析的变量”

而在useProTable中，这种<template #xxx="scope">里的scope.row.xxx都能正确解析，

这是什么原因导致的呢？

![CleanShot 2023-08-26 at 09 10 30@2x](https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/fdd66761-75c2-4410-84ac-c16567e55e1e)

**Comment by HalseySpicy** [comment]
vscode 好像没报错

**Comment by HalseySpicy** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/7cf57feb-cc78-43cc-a176-4c99c7e2b1a5)
