### ISSUE TITLE
Drawer在safari浏览器上会被遮挡，在安卓上没问题

### ISSUE THREAD

**Issue by SwankyTigerYY** [HalseySpicy/Geeker-Admin#303]
![1089d0c20d7e9141c49ddc1c0fbc798](https://github.com/HalseySpicy/Geeker-Admin/assets/24326903/b167bb4c-d42f-4895-9657-1c7e225e38a9)
![9df0dc99b639776d4cccb9a5ccbd97e](https://github.com/HalseySpicy/Geeker-Admin/assets/24326903/d6ca1654-0cce-450c-8d4b-8b64a79fe37b)

**Comment by HalseySpicy** [comment]
设置宽度为百分比
