### ISSUE TITLE
头部导航和侧边栏导航同时使用

### ISSUE THREAD

**Issue by haobarry** [HalseySpicy/Geeker-Admin#310]
头部导航和侧边栏导航同时使用， 比如一级菜单在顶部，二级菜单在侧面

**Comment by HalseySpicy** [comment]
#125

**Comment by elarbor** [comment]
在哪里新增菜单啊？
![image](https://github.com/user-attachments/assets/8232b84a-6def-42c5-9a19-1086c20325f3)
