### ISSUE TITLE
是否支持 SearchFormItem 自定义 label

### ISSUE THREAD

**Issue by heavenly-zy** [HalseySpicy/Geeker-Admin#312]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/50657815/850fdbd1-a416-43da-9989-3d11897efa31)
如图，「用户姓名」这一列开启了查询功能，但我想让查询表单直接显示 label 为「姓名」，请问该如何做呢？

![image](https://github.com/HalseySpicy/Geeker-Admin/assets/50657815/2ee5b4c7-5617-48a5-8aa3-3a5b1467b37d)
`SearchProps` 貌似并不支持配置自定义的查询文本

**Comment by HalseySpicy** [comment]
下个版本更新

**Comment by HalseySpicy** [comment]
已更新
