### ISSUE TITLE
大佬，文档地址无法打开了，您有时间瞅瞅

### ISSUE THREAD

**Issue by HuanJingAAA** [HalseySpicy/Geeker-Admin#314]

**Comment by HalseySpicy** [comment]
https://docs.spicyboy.cn/ 访问不了，应该需要翻墙，我部署在 vercel 上的
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/c38f5f38-d21b-4d35-a1d9-68eb3a6bdf7c)
