### ISSUE TITLE
同一个path如何多次打开

### ISSUE THREAD

**Issue by zhupengfeivip** [HalseySpicy/Geeker-Admin#315]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/30720809/38fbe300-8278-46e2-86af-f93a763caac5)

如图，使用场景如下
用户进入设备列表页面，然后在设备列表上点某一个设备进入设备详情。打开一个新的标签，点另一个设备再打开一个新的标签。

问题描述
目前可以打开两个标签，但是内容始终显示前一个页面的内容。两个页面的URL不同。
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/30720809/0ec43aa9-3788-430e-944b-e02969f3ffa5)
页面一显示正常
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/30720809/9a980b62-8d90-425a-b910-8a5b71e4bfc5)
页面二的URL正常，但是内容显示的不是页面一的。

**Comment by HalseySpicy** [comment]
![动画1](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/b7282828-8d6c-44b2-a9b8-3b4add974b31)

**Comment by zhupengfeivip** [comment]
可能是我代码里哪里有问题，目前也未找到原因。
暂时用params解决了，已经提交测试。

有网友说4.1以后，params无效。
地址：https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22
看内容应该是没有定义path的情况下，用params无效。
```js
					<el-table-column label="设备名称">
						<template #default="{ row }">
							<router-link
								:underline="false"
								:to="{ name: 'info', path: '/device/info', params: { sn: row.sn } }"
								replace
								style="text-decoration: none"
							>
								<span>{{ row.deviceName }}</span>
							</router-link>
						</template>
					</el-table-column>
```
