### ISSUE TITLE
prettier与stylelint配置冲突

### ISSUE THREAD

**Issue by lvchunjia** [HalseySpicy/Geeker-Admin#318]
拉下代码install后，每个vue文件都提示警告：Unknown word (CssSyntaxError)。
经测试，将vscode其余插件都禁用，只保留prettier与stylelint时会有此警告（只保留stylelint无警告），猜测应该是prettier与stylelint配置有冲突。
<img width="863" alt="Snipaste_2023-09-23_18-22-08" src="https://github.com/HalseySpicy/Geeker-Admin/assets/72855658/252944ab-9024-48c9-a2ce-46121961d222">

**Comment by HalseySpicy** [comment]
按照规范来，我这没问题o
https://docs.spicyboy.cn/guide/standard.html
