### ISSUE TITLE
TreeFilter组件最好支持手动刷新方法和默认展开层级

### ISSUE THREAD

**Issue by huguodong** [HalseySpicy/Geeker-Admin#319]
1.左边是组织树右边是组织列表，当我添加一个组织的时候希望左边能同步刷新
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/12368323/475c81d2-81fc-40b4-8e85-245742f5af04)
2.默认TreeFilter是展开全部层级的，如果层级过多会不会显示很乱，希望可以指定默认展开层级，比如默认展开2层

**Comment by selfly** [comment]
相同需求，目前树表展示完美，不过有添加或更新操作，左边的树就很不友好了。
最好是能刷新指定的节点，目前是全量数据

**Comment by HalseySpicy** [comment]
https://github.com/HalseySpicy/Geeker-Admin/commit/db66a6bea2860a2ceee583c141d76e33679f5a25
