### ISSUE TITLE
您好， 我觉得这个 ProTable 概念很好， 与我们的想法不谋而合， 提一些意见

### ISSUE THREAD

**Issue by mei-rune** [HalseySpicy/Geeker-Admin#322]
您好， 我觉得这个 ProTable 概念很好， 与我们的想法不谋而合， 提一些意见。

我们也做过类似的想法， 我们遇到的问题更好复杂

## 1.  搜索的问题
我们的搜索很复杂， 选项很多， 表格搜索区域 放在表格顶部的话占用空间太大， 虽然有折叠和展开功能， 但是用户常常一些选项在被折叠后，对搜索结果产生疑问。

我们希望增加一个新模式（由程序员决定用哪个模式），放在表格的 右边，默认折叠， 点高级搜索时展开，放在右边的好处时，选项无论多少都是可以放得下，不会难看，如下图
![图片](https://github.com/HalseySpicy/Geeker-Admin/assets/1052632/3bc31814-b229-4680-a389-86c00dfc61b2)

## 2. 统计功能（这个我不确定是不是通用需求）

![图片](https://github.com/HalseySpicy/Geeker-Admin/assets/1052632/2da5fb18-2d28-425b-95ad-9a3136858756)

**Comment by maxpowercode** [comment]
组合查询是一个挺好的功能!

**Comment by haobarry** [comment]
选项多应该拆开  放在一个页面不合适

**Comment by mei-rune** [comment]
@haobarry 不能这么说，用户的表格有 10 字段， 有8 个作为搜索条件， 这种情况不少。

**Comment by HalseySpicy** [comment]
您好，自行添加即可，目前不添加这些功能
