### ISSUE TITLE
proTable分页bug

### ISSUE THREAD

**Issue by Nahane** [HalseySpicy/Geeker-Admin#326]
如果组件不使用api获取数据，直接给data属性赋值List，则无法修改useTable中的pageable参数，也无法取消默认分页

**Comment by HalseySpicy** [comment]
已修复：

**Comment by HalseySpicy** [comment]
> 已修复：

![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/f44ca46c-f83b-4501-be1b-385b60568ca3)
