### ISSUE TITLE
 ERROR  项目启动，登录和退出时，时不时会报错： [vite] http proxy error at /geeker/login:   15:04:21   Error: getaddrinfo ENOENT www.fastmock.site     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) (x2)

### ISSUE THREAD

**Issue by Banqc0621** [HalseySpicy/Geeker-Admin#330]
[vite] http proxy error at /geeker/login:   15:04:21   Error: getaddrinfo ENOENT www.fastmock.site     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) (x2)

**Comment by HalseySpicy** [comment]
fastmock 不能用就切换成这个：
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/0ef75f5d-5e8e-4d46-ae4d-6358948b7d4d)
