### ISSUE TITLE
遇到一个分页回调上的问题

### ISSUE THREAD

**Issue by Leryoo** [HalseySpicy/Geeker-Admin#340]
大佬好 今天在开发过程中遇到一个问题 不确实后端还是我这边的问题 
就是现在有个页面是不需要分页的 后台就没给我返回的有page size那些分页数据 然后我就在我的Protable属性上加上了`:pagination="false"` 但是加上了这个属性后表格就报错
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/46736410/8e719cdd-974c-4862-acf3-4c974c03b79f)
已经测试过不加就不会报错
但是不加这个属性会自动在请求上拼接page和size 并且请求会发送两次 找了很久没找到原因 想请教下原因
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/46736410/4683c11a-fd35-47a6-af26-6b4272bb7958)

**Comment by HalseySpicy** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/de5df8f9-88d9-4805-8d46-2cbdbe912f7e)
