### ISSUE TITLE
拖拽功能异常

### ISSUE THREAD

**Issue by enjoy-myLife** [HalseySpicy/Geeker-Admin#341]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/73453769/23382484-0288-4654-9f25-81b16884aa04)

**Comment by HalseySpicy** [comment]
请把复现步骤贴在这里

**Comment by enjoy-myLife** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/73453769/34e2a94c-97bf-450c-a41f-699d67bcde66)

**Comment by enjoy-myLife** [comment]
当列数少的时候更容易复现，比如当总列数为3个，然后拖拽最后一列，就会让最后一列和最右侧脱离；
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/73453769/7a7849f9-807c-489c-a4d5-6e5968ed71c9)

**Comment by SwankyTigerYY** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/24326903/6157a37a-50b4-499c-ac4f-473ac870223e)
再点击展开，出现这面这个。每次需要在@darg-sort处理。
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/24326903/5b99231a-2c52-41b2-b1af-b174abaad4e9)
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/24326903/4b2a0b3a-a31b-45cd-94eb-218f2eb9d37e)

**Comment by SwankyTigerYY** [comment]
@HalseySpicy

**Comment by HalseySpicy** [comment]
无法修改
