### ISSUE TITLE
菜单meta中少个新窗口打开

### ISSUE THREAD

**Issue by SwankyTigerYY** [HalseySpicy/Geeker-Admin#342]
本人有这个需求是因为从一个本来是protable的页面点击"isFull": true的页面再点击chrome的回退按钮，会出现table拥挤在左侧的BUG
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/24326903/eea547e3-6360-4a29-bcb6-83a5b76fb1c6)

**Comment by SwankyTigerYY** [comment]
我现在用的isLink去实现的新页打开，感觉很奇怪

**Comment by HalseySpicy** [comment]
目前我没有这个需求
