### ISSUE TITLE
echarts 中的图表，切换全屏后变到最小

### ISSUE THREAD

**Issue by ThisGoLive** [HalseySpicy/Geeker-Admin#343]
1. 浏览器 ：火狐  Edge
2. 版本：1.2.0， https://admin.spicyboy.cn/ 打不开，本地启动的最新的 master 分支
3. 复现流程：登录admin 后，打开 echarts 下任意图表，然后再打开 任意页签。点击 全屏，再点击 取消全屏，切换回 最开始的echarts 页签下，就可以复现。

**Comment by hirohitosann** [comment]
额，解决了，`onActivated(() => {
  if (chartInstance.value) {
    chartInstance.value.resize();
  }
});`

**Comment by tlerbao** [comment]
mark

**Comment by sizhuxuan** [comment]
> 额，解决了，`onActivated(() => { if (chartInstance.value) { chartInstance.value.resize(); } });`

老哥，我现在碰到 option更新了，但是echarts不更新，不知道咋回事。直接传一个静态数据是可以显示的

**Comment by hirohitosann** [comment]
> > 额，解决了，`onActivated(() => { if (chartInstance.value) { chartInstance.value.resize(); } });`
> 
> 老哥，我现在碰到 option更新了，但是echarts不更新，不知道咋回事。直接传一个静态数据是可以显示的
组件内部watch监听option变化，变化后执行draw函数重新setOption图表

**Comment by hirohitosann** [comment]
> > 额，解决了，`onActivated(() => { if (chartInstance.value) { chartInstance.value.resize(); } });`
> 
> 老哥，我现在碰到 option更新了，但是echarts不更新，不知道咋回事。直接传一个静态数据是可以显示的


组件内部watch监听option变化，变化后执行draw函数重新setOption图表

**Comment by sizhuxuan** [comment]
> onActivated(() => { if (chartInstance.value) { chartInstance.value.resize(); } });

好的老哥，onActivated(() => { if (chartInstance.value) { chartInstance.value.resize(); } }); 你这段代码加到<ECharts :option="option" />这个组件里面吗？

**Comment by hirohitosann** [comment]
> > onActivated(() => { if (chartInstance.value) { chartInstance.value.resize(); } });
> 
> 好的老哥，onActivated(() => { if (chartInstance.value) { chartInstance.value.resize(); } }); 你这段代码加到这个组件里面吗？能贴个demo吗


vue引入onActivated，上述代码直接复制到echarts组件即可

**Comment by limuen** [comment]
#419
