### ISSUE TITLE
ProFrom运行无效果

### ISSUE THREAD

**Issue by yumengbdw** [HalseySpicy/Geeker-Admin#345]
用作者的proFrom的代码在我的项目中运行效果
![11](https://github.com/HalseySpicy/Geeker-Admin/assets/11400046/1da2dd21-6494-409b-ac4e-5026e1274d38)
坐着项目运行的效果。
![22](https://github.com/HalseySpicy/Geeker-Admin/assets/11400046/c1769ef1-6430-4d50-a347-27102fc35ed7)

实际我的项目并没有加载成功 el-form  和el-form-item之类的。是哪里需要配置吗

**Comment by HalseySpicy** [comment]
elemnt-plus 全局引入
