### ISSUE TITLE
页签切换

### ISSUE THREAD

**Issue by DEVCODE001** [HalseySpicy/Geeker-Admin#346]
菜单列表切换，在切换已打开过的页签（已调整分页数量），切换回去页面会重新发起请求并且上次选择的分页数据也会回复成默认数量

**Comment by DEVCODE001** [comment]
目前不知道哪里出问题导致的，我看demo不存在这种问题

**Comment by HalseySpicy** [comment]
也许是你后端数据返回问题

**Comment by HalseySpicy** [comment]
![Uploading 微信图片_20231113150636.png…]()

**Comment by DEVCODE001** [comment]
在demo的protable，把代码copy过来是正常的，只有路由配置没有protable就存在这种问题，
截图上方选中框有问题，下方选中框不存在问题，现在指向的几个文件完全是一致的，自定义的路由地址的存在这种问题，页签切换后再切换回来会重新加载。
![code001](https://github.com/HalseySpicy/Geeker-Admin/assets/148427714/bae2362d-7ff9-4676-ae54-c4a8397b057d)

**Comment by HalseySpicy** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/b51a6148-ff70-4903-b1af-9db07bb14d5c)

**Comment by HalseySpicy** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/511341f1-dadd-429e-9633-ccedc38726bf)

**Comment by DEVCODE001** [comment]
问题已解决，感谢大佬
