### ISSUE TITLE
render渲染component动态组件失效

### ISSUE THREAD

**Issue by shuqingsonglove** [HalseySpicy/Geeker-Admin#348]
您好，我在定义表格配置配置项时出现一个问题：进行render自定义渲染逻辑时，使用渲染失败。 如图：
1.![question](https://github.com/HalseySpicy/Geeker-Admin/assets/136777604/2a7f3949-e991-4c54-8c9f-9ccccc99b4cf)
2![question1](https://github.com/HalseySpicy/Geeker-Admin/assets/136777604/1a405ab9-24df-4bc1-b86e-5ce6b2b34f24)
3.![question2](https://github.com/HalseySpicy/Geeker-Admin/assets/136777604/20b5462c-7c7a-43cd-b447-e42043dfaaa5)

**Comment by HalseySpicy** [comment]
TSX 语法不支持 component 动态组件，component 动态组件只能在 template 中生效
