### ISSUE TITLE
Protable下拉框检索条件能否支持无限滚动下拉加载呢

### ISSUE THREAD

**Issue by yuyan11-peng** [HalseySpicy/Geeker-Admin#360]
您好，请问下如果数据量很大后端做了分页，检索条件下拉查询的时候滚动加载，我在想用封装的指令还是用elm的无限滚动，目前我是这样做的
![dd18362f422e470f36538994adda569](https://github.com/HalseySpicy/Geeker-Admin/assets/104304493/3bdf278d-6e12-4715-9ff3-4edbf18362c9)
![3fdc8d7f8dc267ea7064651e9f12119](https://github.com/HalseySpicy/Geeker-Admin/assets/104304493/7f434411-4099-4658-abf4-ba60c3ed451a)

**Comment by HalseySpicy** [comment]
使用虚拟列表选择器即可。https://element-plus.org/zh-CN/component/select-v2.html

**Comment by yuyan11-peng** [comment]
谢谢作者大大解答，可是用虚拟列表选择器跟select下拉选择框是一样的吧，也是需要滚动到底部的时候加载下一页。能明白你的意思，用虚拟选择器，一次性发比如9999的size，可是如果超过了9999还是会有数量上的问题，在想用无限滚动还是指令这种还是得一直写 v-infinite-scroll和remote-method的加载方法，所以请教作者大大，不胜感激
