### ISSUE TITLE
iframe引入html本地静态文件失败

### ISSUE THREAD

**Issue by clarehjh** [HalseySpicy/Geeker-Admin#366]
![9508c77c757fd35d509fa33cf3c1513](https://github.com/HalseySpicy/Geeker-Admin/assets/83281667/e8e5b269-56f3-4a2f-9232-5658cb9fd5fb)
![568dd199e7f13a0fdbec6dd9d9e7d24](https://github.com/HalseySpicy/Geeker-Admin/assets/83281667/bed70fbf-f132-4251-9fab-83da44ea3f7b)

**Comment by HalseySpicy** [comment]
不清楚
