### ISSUE TITLE
proTable选中多行后，删除某一行，删除的这一行key(id)还在选中的数据中

### ISSUE THREAD

**Issue by DongWenHai** [HalseySpicy/Geeker-Admin#369]
proTable选中多行后，删除某一行，删除的这一行key(id)还在选中的数据中,这是不是BUG
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/34147892/e5db43b1-e45e-4ebe-8a6f-24f792af7f2e)

**Comment by HalseySpicy** [comment]
proTable.value.clearSelection()

**Comment by dingling001** [comment]
> proTable.value.clearSelection()

如何取消某一行的选中状态
