### ISSUE TITLE
编译出错提示dataScreen

### ISSUE THREAD

**Issue by cnokany** [HalseySpicy/Geeker-Admin#372]
- error TS2769: No overload matches this call.
  Overload 1 of 2, '(intervalId: string | number | Timeout | undefined): void', gave the following error.
    Argument of type 'Timer' is not assignable to parameter of type 'string | number | Timeout | undefined'.
      Property '[Symbol.dispose]' is missing in type 'Timer' but required in type 'Timeout'.
  Overload 2 of 2, '(id: number | undefined): void', gave the following error.
    Argument of type 'Timer' is not assignable to parameter of type 'number'.

161   clearInterval(timer!);

**Comment by HalseySpicy** [comment]
无法复现
