### ISSUE TITLE
在线预览 👀 打开后，无法登录，求修复下，求瞻仰

### ISSUE THREAD

**Issue by shenbinglife** [HalseySpicy/Geeker-Admin#376]
在线预览打开后，无法登录，求修复下，求瞻仰下内容

**Comment by HalseySpicy** [comment]
换个网络试试，我这可以的
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/93f6828f-71d2-457d-9e05-d34eae5fb21f)

**Comment by shenbinglife** [comment]
可以了。 尝试了翻墙才能打开，应该时mock的这个地址需要翻一下，不然的话就是公司网络问题了

https://mock.mengxuegu.com/mock/629d727e6163854a32e8307e/geeker/login
