### ISSUE TITLE
echarts 图标不显示，可能是什么原因

### ISSUE THREAD

**Issue by tlerbao** [HalseySpicy/Geeker-Admin#377]
如下图，我原封不懂的把演示代码的lineChart代码复制到我得组件中，什么也不显示，控制台也不报错，

请问可能是什么原因造成的呢？

![CleanShot 2023-12-28 at 19 25 52@2x](https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/80693774-ff7a-4c24-a16f-9dd95ee9eb30)

<img width="1713" alt="CleanShot 2023-12-28 at 19 29 49@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/14e6cde8-262f-45bd-b039-9d533f590c41">

**Comment by HalseySpicy** [comment]
我的是按需引入的哦，你可以看看有报错没

**Comment by tlerbao** [comment]
@HalseySpicy 奇怪的是啥报错都没有

**Comment by tlerbao** [comment]
@HalseySpicy 我测试了一下，在<div ref="echartsRef" class="card content-box"></div> 外面套一个div 就什么不显示了，这页面只能有一个图标元素，别的什么也不能有？
<img width="706" alt="CleanShot 2023-12-28 at 21 17 54@2x" src="https://github.com/HalseySpicy/Geeker-Admin/assets/20442232/0a372654-8ffb-49be-b097-ef48e6e1742b">

**Comment by tlerbao** [comment]
> 没宽高啊

嗯发现了，close
