### ISSUE TITLE
自定义指令v-auth当作用在el-dropdown-item上时失效

### ISSUE THREAD

**Issue by PathfinderAx** [HalseySpicy/Geeker-Admin#378]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/45918905/0cb213ef-a907-40c7-8cca-534bed249af7)

      <template #tableHeader>
        <el-button v-auth="'add'" type="primary" @click="openAmdDialog('新增')">新增</el-button>
        <el-dropdown>
          <el-button type="primary">
            导出<el-icon class="el-icon--right"><arrow-down /></el-icon>
          </el-button>
          <template #dropdown>
            <el-dropdown-menu>
              <el-dropdown-item v-auth="'exportTxt'">导出为TXT</el-dropdown-item>
              <el-dropdown-item v-auth="'exportExcel'">导出为Excel</el-dropdown-item>
            </el-dropdown-menu>
          </template>
        </el-dropdown>
      </template>
如图，在上方代码中使用el-dropdown组件时，当自定义指令v-auth当作用在el-dropdown-item上时失效，还是会全部展示，且控制台会报出警告

**Comment by HalseySpicy** [comment]
可以尝试使用 hooks 方式
