### ISSUE TITLE
页面加载时会闪屏，尤其是有table 的页面

### ISSUE THREAD

**Issue by 156704883** [HalseySpicy/Geeker-Admin#379]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/49087478/3c6b9766-f213-4b0c-83c4-508563f22bff)
是这个 loading 引起的吗？感觉有一个黑色遮罩闪一下

**Comment by HalseySpicy** [comment]
嗯

**Comment by tlerbao** [comment]
@HalseySpicy 同问一下，一些请求我加了 `{ headers: { noLoading: true }` ,但是怎么感觉好像还是有呢，还是有遮罩一下

**Comment by HalseySpicy** [comment]
之前更新了，
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/8fd82881-3fdb-4db3-b920-136acfcbd865)
