### ISSUE TITLE
ProTable显示 可以适配下cascader吗，如下列的city

### ISSUE THREAD

**Issue by hirohitosann** [HalseySpicy/Geeker-Admin#382]
`/* 表格*/
const columns: ColumnProps<any>[] = [
  { type: "index", label: "序号", width: 80 },
  { prop: "username", label: "用户名", },
  { prop: "bindRoleID", label: "权限" , tag: true,enum:getRoleOptionsAPI,fieldNames: { label: "label", value: "value"}},
  { prop: "loginStatus", label: "状态" , tag: true,enum:getUserStatausOptionsAPI,fieldNames: { label: "label", value: "value"}},
  { prop: "city", label: "所在城市",enum:regionData,fieldNames: { label: "label", value: "value", children:[label: "label", value: "value", children:[label: "label", value: "value"]]},}
  { prop: "createTime", label: "创建时间" },
  { prop: "updateTime", label: "更新时间" },
  { prop: "mark", label: "备注" },
  { prop: "operation", label: "操作", fixed: "right", width: 120 }
];`

**Comment by hirohitosann** [comment]
`{ prop: "city", label: "所在城市",enum:regionData,fieldNames: { label: "label", value: "value", children:[label: "label", value: "value", children:[label: "label", value: "value"]]},}`

**Comment by HalseySpicy** [comment]
默认支持的
