### ISSUE TITLE
组件不渲染问题

### ISSUE THREAD

**Issue by TomSonghang** [HalseySpicy/Geeker-Admin#39]
点击左边导航栏或者顶部导航栏切换组件时，会出现内容区组件不渲染问题，如果出现该问题之后，后续不管怎么点击，内容区组件就一直不会渲染，一直处于空白状态

**Comment by HalseySpicy** [comment]
你好，这个问题应该只有开发的时候才会遇到，我开发中同样遇到该问题，强制刷新页面就好了，大概是 vite 热更新问题

**Comment by TomSonghang** [comment]
感谢回复，如果是打包发到服务器上之后就不会有类似问题了是吧？

**Comment by HalseySpicy** [comment]
目前我打包之后是没有遇到这个问题的
