### ISSUE TITLE
webstorm打开工程代码，很多vue文件报错

### ISSUE THREAD

**Issue by iloveleeyan** [HalseySpicy/Geeker-Admin#390]
![ws报错](https://github.com/HalseySpicy/Geeker-Admin/assets/16837428/bfe839bd-dbc2-475a-b514-d0abffa40f09)

如图，webstorm版本是 WebStorm 2022.3.4

大家能帮忙看看么，应该是ws的设置问题，但是我百度找了很多设置都没能解决

**Comment by HalseySpicy** [comment]
推荐使用 VSCode，webstorm 没配置过

**Comment by tlerbao** [comment]
@iloveleeyan 你的版本太旧了，新版本没问题
