### ISSUE TITLE
将Vue的版本升级到3.4.19后，控制台出现警告

### ISSUE THREAD

**Issue by qtanran** [HalseySpicy/Geeker-Admin#393]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/48440870/3d12acec-a6ac-4a40-87b3-cda6805a61f2)

不影响正常使用

发现了一个相同的issues

https://github.com/vueuse/vueuse/issues/3794

**Comment by qtanran** [comment]
使用表格组件的时候

**Comment by HalseySpicy** [comment]
拉最新代码
