### ISSUE TITLE
 请问下我想要添加我们ui设计的icon，在iconfont中，我应该怎么使用到菜单栏中呢

### ISSUE THREAD

**Issue by Howie7793** [HalseySpicy/Geeker-Admin#397]
请问下我想要添加我们ui设计的icon，在iconfont中，我应该怎么使用到菜单栏中呢，我目前是使用element中的icon，直接在json中通过name使用就行了。   就是不知道怎么使用我自定义的iconfont

**Comment by HalseySpicy** [comment]
渲染时，自行判断即可

**Comment by Howie7793** [comment]
好的，找到了，谢谢，我原本以为是在配置中修改即可。是我想错了。
