### ISSUE TITLE
研究很久的问题，望解答。 表格的查询按钮字段参数如何和与表格column的兼容，默认字段为空值

### ISSUE THREAD

**Issue by akangwu** [HalseySpicy/Geeker-Admin#398]
<img width="1436" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/43903377/ec6137cd-4586-4a83-a56c-ec6789326c34">

**Comment by wjiangwang** [comment]
defaultValue 有这个配置

<img width="741" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/39005591/e682d8e4-9afc-424e-9c90-60f5e9ee4a5c">

**Comment by HalseySpicy** [comment]
不支持，得手动改 protable 源码哟
