### ISSUE TITLE
不是，有人试过i18n吗？是个摆设吗？

### ISSUE THREAD

**Issue by 2g8** [HalseySpicy/Geeker-Admin#399]
模板里面 
{{ t('home.welcome') }}

测试过吗？还是我用法不对？

**Comment by zhuman90** [comment]
你怎么引入的

**Comment by suyuan0** [comment]
看作者模版里面是 $t
<img width="504" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/101795206/a042edf6-6d47-44a5-aa27-def0000e0fb7">

**Comment by limuen** [comment]
https://github.com/HalseySpicy/Geeker-Admin/blob/master/src/layouts/components/Tabs/components/MoreButton.vue
