### ISSUE TITLE
本地配置两个请求地址，build:dev打包后不生效

### ISSUE THREAD

**Issue by huxiguo** [HalseySpicy/Geeker-Admin#402]
本地配置了两个接口地址，build:dev后不生效，为什么，有大神知道怎么解决吗

**Comment by LiuC123** [comment]
同求，配置了/api和/api1的proxy，不生效。一直好像都api生效，api1的请求永远都是404

**Comment by huxiguo** [comment]
你是dev开发环境还是build打包后的环境

**Comment by HalseySpicy** [comment]
dev 之后代理不生生效的，proxy 只有在本地生效
