### ISSUE TITLE
TreeFilter

### ISSUE THREAD

**Issue by xzhdev** [HalseySpicy/Geeker-Admin#403]
<img width="1483" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/102580603/4a16d672-84e1-4b1c-8c2b-08a85d029505">
问下为什么单选要限制默认值必须是string类型

**Comment by HalseySpicy** [comment]
你可以试试不默认，单选会不会报错，之前我写的时候会报错

**Comment by xzhdev** [comment]
@HalseySpicy 没明白大佬您的不默认是什么意思，我的意思是这样写，默认值传number值，例如传10 ，selected也就变成空字符串，不能设置数字类型的默认值高亮了，我多加了一个number类型，像这样
<img width="776" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/102580603/5d249228-6af6-4bba-a593-3cdae9010582">

**Comment by attachmentList** [comment]
我改成number 不报错，可能 pnpm update 升级包导致？
