### ISSUE TITLE
login api无法返回data data 打印是undefined

### ISSUE THREAD

**Issue by wushenhaoyu** [HalseySpicy/Geeker-Admin#405]
我这已经成功连接我的后端了，后端这边反应正常而且用postman能成功登陆并且返回相应的数据，但是vue中的请求能成功发送，但是收不到回来的data，一直都是undefined怎么回事？
![Uploading image.png…]()

**Comment by tlerbao** [comment]
图裂了，不行咱们贴个正常的控制台网络那边的调试信息截图看看呢？

**Comment by wushenhaoyu** [comment]
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/129858837/e42ee42a-2fda-4401-8a2f-0a6c497a23e0)
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/129858837/2cf81a95-70f6-4cf6-86e2-0580861e99d5)
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/129858837/004df3fd-5a7b-4368-929a-92d5dc9444fa)
后端那里没问题，相应的数据已经发出去了，但是就是接收不到

**Comment by tlerbao** [comment]
咱们看下 你携带正确的 access_token 了吗？
主要看响应选项卡

**Comment by wushenhaoyu** [comment]
access_token是不是随便写个啥就行啊，我服务器那边是按自己规则生成的，
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/129858837/238680c2-0807-49f1-8518-8fbce3c367c4)
z这个是postman测试的结果

**Comment by wushenhaoyu** [comment]
想起来了，是不是那个东西放在header里来着？
