### ISSUE TITLE
动态路由界面访问之后，页面变成空白

### ISSUE THREAD

**Issue by rainingyoyo** [HalseySpicy/Geeker-Admin#407]
动态路由界面访问之后，页面变成空白`
并且打印警告信息：Component inside <Transition> renders non-element root node that cannot be animated. 

经查询组件中包裹的不是一个单节点元素。 transition 中不能有多个root元素

解决: 把我们的组件都包裹成单节点,最外层套div

解决方案就是在 src/layouts/components/Main/index.vue 中的
`
<transition appear name="fade-transform" mode="out-in">
        <keep-alive :include="keepAliveName">
          <component :is="createComponentWrapper(Component, route)" v-if="isRouterShow" :key="route.fullPath" />
        </keep-alive>
      </transition>
`

改为
`
<transition appear name="fade-transform" mode="out-in">
        <div>
        	<keep-alive :include="keepAliveName">
	          <component :is="createComponentWrapper(Component, route)" v-if="isRouterShow" :key="route.fullPath" />
	        </keep-alive>
        </div>
      </transition>
`

**Comment by HalseySpicy** [comment]
图片你好像没上传，之前 issues 提过这个问题 https://github.com/HalseySpicy/Geeker-Admin/issues/250

**Comment by rainingyoyo** [comment]
我的是复制的代码，估计超长了，我在后面加一下，但是在新的版本似乎并没有解决这个问题

**Comment by rainingyoyo** [comment]
<transition appear name="fade-transform" mode="out-in">
        <keep-alive :include="keepAliveName">
          <component :is="createComponentWrapper(Component, route)" v-if="isRouterShow" :key="route.fullPath" />
        </keep-alive>
      </transition>
改为
<transition appear name="fade-transform" mode="out-in">
        <div>
        	<keep-alive :include="keepAliveName">
	          <component :is="createComponentWrapper(Component, route)" v-if="isRouterShow" :key="route.fullPath" />
	        </keep-alive>
        </div>
      </transition>

**Comment by HalseySpicy** [comment]
transition 必须只有一个根
