### ISSUE TITLE
vite-plugin-svg-icons 插件已停更2年 是否考虑更换插件实现引入本地svg功能

### ISSUE THREAD

**Issue by Canroc** [HalseySpicy/Geeker-Admin#411]
在npm初始化时有大量的组件已弃用提示，经查验发现这些插件是vite-plugin-svg-icons，unplugin-vue-setup-extend-plus下的引用插件，在vite-plugin-svg-icons的github站点上查看，此插件已停更2年了。
后期版本是否会考虑使用其他方式来实现本地svg的自动引入。
![1711864173853](https://github.com/HalseySpicy/Geeker-Admin/assets/84954229/14be09b6-6b1e-4c57-b376-f5fd82270866)

**Comment by HalseySpicy** [comment]
可以自行替换
