### ISSUE TITLE
v-copy 在复制失败时，仍提示复制成功

### ISSUE THREAD

**Issue by j0hnh** [HalseySpicy/Geeker-Admin#413]
此处应优化 `ElMessage` 提示的位置，分别移入 `try` 和 `catch` 块内

https://github.com/HalseySpicy/Geeker-Admin/blob/363c670b02d3f9e7fcded9db3b2b6de1bc6389ed/src/directives/modules/copy.ts#L25-L35

**Comment by limuen** [comment]
#418
