### ISSUE TITLE
官方最新的DevTools7插件安装后无法与vite插件兼容，望作者大大优化下

### ISSUE THREAD

**Issue by zhangzz0213** [HalseySpicy/Geeker-Admin#424]
官方推出的调试插件十分好用，我尝试安装并配置到vite.config.ts后，无法兼容；
#import VueDevTools from "vite-plugin-vue-devtools";
#plugins: [VueDevTools(), ...createVitePlugins(viteEnv)],  
--上述配置后 pnpm dev启动项目时会出现
➜  Local:   http://localhost:5173/ 
➜  Vue DevTools: Open http://localhost:5173/__devtools__/ 
仅能正常打开plugins配置中一个参数，比如上述配置VueDevTools()是第一位可正常打开，项目则无法打开，
颠倒顺序后项目可打开，调试页面无法打开，**提示404找不到页面**
<img width="411" alt="54875782-7362-4f8c-85E3-159023DFD7B3" src="https://github.com/HalseySpicy/Geeker-Admin/assets/63530988/25c8ca2e-b119-4513-95ba-56ca74d601e2">
<img width="358" alt="E519E88A-D860-4334-A80A-9700885D5649" src="https://github.com/HalseySpicy/Geeker-Admin/assets/63530988/8b786f6e-9540-4d3c-8925-1d49a61d801b">

**Comment by HalseySpicy** [comment]
没用过😧，一直用的谷歌 devtools

**Comment by MissYooo** [comment]
https://github.com/vuejs/devtools-next/issues/278#issuecomment-2021745201
参考这个解决方案，在注册 vite-plugin-html 插件前先注册 Vue DevTools 就可以正常使用。

**Comment by MissYooo** [comment]
https://github.com/vuejs/devtools-next/issues/278#issuecomment-2021745201
参考这个解决方案，在注册 vite-plugin-html 插件前先注册 Vue DevTools 就可以正常使用。

**Comment by HalseySpicy** [comment]
https://github.com/HalseySpicy/Geeker-Admin/commit/58bfe44a42ff58bc7342dc287b3317d73cda208e
