### ISSUE TITLE
Protable如何在SearchColumns中添加关键字搜索的input？

### ISSUE THREAD

**Issue by cizkey** [HalseySpicy/Geeker-Admin#426]
Protable的SearchColumns读取的columns配置，但是很多场景下，SearchColumns中还会有关键字搜索的input输入框，请问要如何添加？

**Comment by HalseySpicy** [comment]
element 支持的都支持，只是写成 json 配置了

**Comment by cizkey** [comment]
> element 支持的都支持，只是写成 json 配置了

不是这个意思。

是 关键字这个搜索条件，不应该显示在columns里面，现在是可以通过配置一个 column
{ prop: 'keywords', label: '关键字', isShow: false, search: { el: 'input', placeholder: '请输入关键字' }} 
这种配置来实现，但是逻辑上来 ‘关键字’ 不应该在列配置里面。

我觉得可能需要提供一个额外的extSeachColumns，自定义配置table的搜索栏

**Comment by HalseySpicy** [comment]
search 不是有label 和 key 嘛
<img width="1183" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/b0fd5bad-1b57-496f-9204-9d6557c04fc7">

**Comment by HalseySpicy** [comment]
自行改造即可
