### ISSUE TITLE
你能不能有一个通用的方法， 将 table 的属性导出或传入

### ISSUE THREAD

**Issue by mei-rune** [HalseySpicy/Geeker-Admin#427]
table 很多属性如下链接， 而你只提供了很少几个， 有办法提供出来么
https://cn.element-plus.org/zh-CN/component/table.html#table-%E5%B1%9E%E6%80%A7

类似的还有 table column 属性
https://cn.element-plus.org/zh-CN/component/table.html#table-column-api

**Comment by HalseySpicy** [comment]
？
