### ISSUE TITLE
有无编辑单元格的功能

### ISSUE THREAD

**Issue by candyxiong** [HalseySpicy/Geeker-Admin#428]
大佬好，会有需求 用到点击某个单元格后变成可编辑状态，失去焦点则只是显示值。目前看好像需要自己重新写个组件？

**Comment by HalseySpicy** [comment]
https://github.com/HalseySpicy/Geeker-Admin/pull/228

**Comment by candyxiong** [comment]
哦！谢谢！前面没看到这个

**Comment by candyxiong** [comment]
楼主，所以目前可编辑只有input 没有其他的对吧？
