### ISSUE TITLE
路由跳转白屏问题

### ISSUE THREAD

**Issue by gkils** [HalseySpicy/Geeker-Admin#43]
路由跳转偶尔会出现白屏，本地开发也发现过这个问题，以为是vite热更新的问题没在意，但是打包到线上部署后也有这个问题。

检查了前后端路由配置都正常，没有拼写问题或者多余空格。尝试了去掉路由缓存也没有解决问题。

**Comment by HalseySpicy** [comment]
你好，目前这个问题我只在本地遇到过，线上暂时我这里还没发现问题，在你那边这个问题是必现的吗？复现条件是什么？

**Comment by gkils** [comment]
我这边这种情况是必现的，复现条件我还没研究清除造成的原因是什么，没找到。

**Comment by TomSonghang** [comment]
@gkils 请问你解决了吗？我发到内网也同样出现了该问题；
