### ISSUE TITLE
ElementPlusError: [el-input] [API] label is about to be deprecated in version 2.8.0, please use aria-label instead.

### ISSUE THREAD

**Issue by iHTCboy** [HalseySpicy/Geeker-Admin#432]
ElementPlusError: [el-input] [API] label is about to be deprecated in version 2.8.0, please use aria-label instead.
For more detail, please visit: https://element-plus.org/en-US/component/input.html

<img width="699" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/11418363/ed095e2f-2fc4-4328-9801-1d9b9eca56d6">

<img width="1028" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/11418363/91b83d16-6117-4bf4-8645-af17f6aca0e3">

**Comment by ArvinZy** [comment]
我升级了 element-plus 后也遇到这个警告，报错在 SubMenu.vue，但我没找到具体原因
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/16442244/d0a78c7e-3c20-4d42-99da-d38bfcf6efd0)

**Comment by HalseySpicy** [comment]
已解决
