### ISSUE TITLE
使用 npm run build:dev 出现'vue-tsc' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by xiaofuqw123** [HalseySpicy/Geeker-Admin#437]
我在使用npm run build:dev 后出现错误
![微信图片_20240528165509](https://github.com/HalseySpicy/Geeker-Admin/assets/30396217/513b2e80-84d4-48c5-b54f-f20b04c839a4)

**Comment by HalseySpicy** [comment]
环境变量存在问题吧，具体不清楚你怎么安装的

**Comment by HalseySpicy** [comment]
环境变量存在问题吧，具体不清楚你怎么安装的
