### ISSUE TITLE
user角色登录，却可以访问大屏/dataScreen页面

### ISSUE THREAD

**Issue by heshij** [HalseySpicy/Geeker-Admin#45]
![image](https://user-images.githubusercontent.com/42805166/182307906-aeace07e-6477-4418-9083-a5490800bd9b.png)

用户user角色登录，地址栏输入大屏数据dataScreen页面地址，可以访问

**Comment by HalseySpicy** [comment]
你好，这里是故意设置不需要权限访问的，
![image](https://user-images.githubusercontent.com/51069636/182308605-137bad85-0a0d-4f93-8da6-dc94bffadb89.png)

**Comment by HalseySpicy** [comment]
requiresAuth 权限最大

**Comment by heshij** [comment]
好的，谢谢
