### ISSUE TITLE
initParam 里面使用store 里面的数据，改变store数据后请求参数未改变

### ISSUE THREAD

**Issue by huxiguo** [HalseySpicy/Geeker-Admin#450]
initParam 里面使用store 里面的数据，改变store数据后请求参数未改变，有办法让initParam 参数随 store里的数据变化吗？
<img width="1037" alt="Snipaste_2024-06-10_23-10-36" src="https://github.com/HalseySpicy/Geeker-Admin/assets/71011744/6904ee5e-9182-4dba-bb37-dbb3699b74bb">

**Comment by HalseySpicy** [comment]
使用 computed 吧
![WechatIMG156](https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/447c67c6-791c-4f28-a7e7-97fa2cb51c78)
