### ISSUE TITLE
橫屏模式下菜单下拉选项高度超出屏幕高度时会一直闪烁

### ISSUE THREAD

**Issue by paulqiang118** [HalseySpicy/Geeker-Admin#455]
橫屏模式下菜单下拉选项高度超出屏幕高度时会一直闪烁
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/94597227/f07ad3c7-5ede-440b-b1a5-b9fa723db369)

**Comment by HalseySpicy** [comment]
https://github.com/HalseySpicy/Geeker-Admin/issues/201
