### ISSUE TITLE
这个使用了错误的类型或对象是什么问题

### ISSUE THREAD

**Issue by mnn1127** [HalseySpicy/Geeker-Admin#456]
之前就报过这个错，代码没改过，然后莫名其妙的好了。现在又出现这个问题
![Snipaste_2024-06-21_14-25-44](https://github.com/HalseySpicy/Geeker-Admin/assets/99659664/492451d0-d3db-47d9-a51b-01fa71f14de8)
不仅我自己的页面，包括演示文档也有几个报这个错，而且这个错出现之后演示页面的useprotable 会报如下的错误
![Snipaste_2024-06-21_14-26-11](https://github.com/HalseySpicy/Geeker-Admin/assets/99659664/e793e201-918f-4828-88d6-b09573f4d264)

实在定位不到错误那来的，问一下大佬

**Comment by HalseySpicy** [comment]
不清楚你业务，提示你 account 为 undefined

**Comment by mnn1127** [comment]
演示文档也报这个东西，图二也是提示useProTable为undefined，演示文档我没改过

**Comment by HalseySpicy** [comment]
无法复现，确认使用 pnpm i 安装依赖
