### ISSUE TITLE
ProTable 的搜索条件有 cascader级联选择器时， props透传后无法渲染

### ISSUE THREAD

**Issue by undefined-Liu** [HalseySpicy/Geeker-Admin#457]
ProTable 的搜索条件有 cascader级联选择器时，通过columns => search => props 透传的属性checkStrictly和multiple都无法生效。
在components => SearchForm => components => SearchFormItem.vue 的75行 console.log(searchProps.props) 值为undefined。
不清楚是我有改过代码还是怎么的问题
"element-plus": "^2.4.3"
![微信图片_20240621150328](https://github.com/HalseySpicy/Geeker-Admin/assets/36975777/be7e1ace-25d3-4a93-b49b-817e4cc71957)
![微信图片_20240621150347](https://github.com/HalseySpicy/Geeker-Admin/assets/36975777/dbdf0add-d3f0-425c-8c28-e370a33a96f2)
![微信图片_20240621150351](https://github.com/HalseySpicy/Geeker-Admin/assets/36975777/55713934-75da-4c56-a277-45b078ceb0dd)

**Comment by HalseySpicy** [comment]
已解决
