### ISSUE TITLE
页面切换卡着不动的bug

### ISSUE THREAD

**Issue by gaolongge** [HalseySpicy/Geeker-Admin#458]
1. 当页面静止很久时，控制台报错；
2. 点击页面切换路由，页面停留在当前页不动；
3. 只有刷新浏览器时，再切换页面就好了；

![WechatIMG643](https://github.com/HalseySpicy/Geeker-Admin/assets/24975204/239805a0-e088-43fb-b849-bd71c71e375a)

**Comment by HalseySpicy** [comment]
我这无法复现哦
