### ISSUE TITLE
可以考虑把devtools-next工具集成进去

### ISSUE THREAD

**Issue by MrDotYan** [HalseySpicy/Geeker-Admin#459]
<img width="1467" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/45706933/e3c26fc0-fae9-4e67-b062-c7a9bb2cf89f">
可以考虑把devtools-next工具集成进去，我已经集成了，感觉还不错

**Comment by HalseySpicy** [comment]
可以提交 pr

**Comment by MrDotYan** [comment]
PR已提交
