### ISSUE TITLE
搜索栏的样式中 .table-header   .el-button   冲突

### ISSUE THREAD

**Issue by mei-rune** [HalseySpicy/Geeker-Admin#462]
我在表格的搜索按钮旁边加了一个 dropdown ，  dropdown中有一个按钮出问题了， 如下图
![1719568888134](https://github.com/HalseySpicy/Geeker-Admin/assets/1052632/6ab9e5b0-a905-4769-a2fb-75166fdb1c66)

这个控件代码如下

````html
      <el-input style="width: 300px" class="table-input" placeholder="请输入进行快速查询">
        <template #prepend>
          <el-select v-model="select" placeholder="名称" style="width: 95px">
            <el-option label="名称" value="1" />
            <el-option label="部门" value="2" />
            <el-option label="备注" value="3" />
          </el-select>
        </template>
        <template #append>
          <el-dropdown split-button type="primary" @click="handleSearchClick" @command="handleSearchCommand" style="width: 40px">
            <el-icon><Search /></el-icon>
            <template #dropdown>
              <el-dropdown-menu>
                <el-dropdown-item>高级查询</el-dropdown-item>
              </el-dropdown-menu>
            </template>
          </el-dropdown>
        </template>
      </el-input>
````

主要问题是 src\styles\element.scss 中 这一行导致的
![1719569099248](https://github.com/HalseySpicy/Geeker-Admin/assets/1052632/72e8f137-d868-43ba-89c1-94eba275aec5)

我想到的这个问题的解决方法如下

1.  在这一行的  所有 button 上统一加一个  class="table-button"
2.  src\styles\element.scss 中改成如下
![1719569492648](https://github.com/HalseySpicy/Geeker-Admin/assets/1052632/3cbc8e61-0eba-4d94-8558-02e4d85f95e0)

然后就显示正常了， 但是我的这个方式会破坏原来代码的兼容性， 好处也是有的， 以后不管用户向这里放什么都不会影响原来的

请问你有什么好的建议， 能不能改一下， 如果你接受我的建议，但不想自已改， 我可以提供 pull request

**Comment by HalseySpicy** [comment]
<img width="422" alt="image" src="https://github.com/HalseySpicy/Geeker-Admin/assets/51069636/e9b2887d-e776-4343-8133-bbe053f0beaa">
  // 表格 header 样式
  .table-header {
    display: flex;
    gap: 15px;
    justify-content: space-between;
    margin-bottom: 15px;
    .header-button-lf {
      display: flex;
      flex-wrap: wrap;
      gap: 15px 0;
    }
    .header-button-ri {
      flex-shrink: 0;
    }
  }

**Comment by mei-rune** [comment]
有空提交一下， 我好同步一下。
