### ISSUE TITLE
Echarts map 组件按需导入

### ISSUE THREAD

**Issue by CLBing** [HalseySpicy/Geeker-Admin#463]
## 错误
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51859383/ca69c39f-679b-4a4d-827e-49cbd2e2105d)
学习尝试封装组件，echarts 在5.3版本之后分离了 registerMap,当按需导入后就会报错误
![image](https://github.com/HalseySpicy/Geeker-Admin/assets/51859383/0812e6b6-daf9-46de-86cf-fa63058eb3e9)
## 疑问
版本与作者同样为 `v5.5.1`
按照官网教程导入并使用  MapChart 后正常，但我看作者是没有导入的却可以正常使用，想请教下怎么做到的

**Comment by Li-0221** [comment]
你好  你应该是漏看了那个`GeoComponent`
<img width="936" alt="image" src="https://github.com/user-attachments/assets/e0942f6b-bf6f-4524-a9b0-3f3906de686b">

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/70c9ef44-b3a0-42d3-bdef-281b2798e735">

**Comment by Li-0221** [comment]
你报错的原因可能是因为你用的是
`import * as echarts from "echarts/core";`
正确的应该是
`import echarts, { ECOption } from "@/components/ECharts/config";`
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/5ca8dca4-a706-49d1-8061-328f902201c6">
