### ISSUE TITLE
校验Form、富文本编辑器等textarea文本框内无法回车换行

### ISSUE THREAD

**Issue by hxp-plus** [HalseySpicy/Geeker-Admin#471]
使用当前 [官方在线demo](https://admin.spicyboy.cn/)  ，进入 校验Form 、 富文本编辑器 这2个页面，尝试在textarea文本框中输入回车来换行：
![image](https://github.com/user-attachments/assets/f3f69d40-6d71-4b76-907a-3215e4a96a3f)
![image](https://github.com/user-attachments/assets/830fb638-5fa3-4c55-8ddc-c4b1e5249d47)
换行没有反应，但是别的地方已经换行的文本可以粘贴进来。

而 element-plus 原本的 textarea 类型输入框，支持换行，可以在 [这里](https://element-plus.org/zh-CN/component/input.html) 测试：
![image](https://github.com/user-attachments/assets/b83f83d3-60e3-4fbf-931d-16dd5099a99a)

此问题导致富文本编辑器无法正常使用。我的浏览器版本如下：

```
Google Chrome : 126.0.6478.127 (Official Build) (64-bit) (cohort: Stable)
Revision : a435861f0ca363a64f7485619ee5939833823fce-refs/branch-heads/6478@{#1592}
OS : Windows 11 Version 23H2 (Build 22631.3880)
JavaScript : V8 12.6.228.21
User Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
```

打开官方Demo，加载时打开F12的console，控制台无报错。

**Comment by hxp-plus** [comment]
初步定位问题为 https://github.com/HalseySpicy/Geeker-Admin/commit/cb4e8b0d597ee73db4543338225d30238a77c7ca 导致，涉及的相关代码（103-114行）如下：
```typescript
const keyboardOperation = (event: KeyboardEvent) => {
  if (event.key === "ArrowUp") {
    event.preventDefault();
    keyPressUpOrDown(-1);
  } else if (event.key === "ArrowDown") {
    event.preventDefault();
    keyPressUpOrDown(1);
  } else if (event.key === "Enter") {
    event.preventDefault();
    handleClickMenu();
  }
};
```

**Comment by HalseySpicy** [comment]
https://github.com/HalseySpicy/Geeker-Admin/pull/475
