### ISSUE TITLE
配置多个代理服务器

### ISSUE THREAD

**Issue by zsyhb** [HalseySpicy/Geeker-Admin#479]
求助：为什么我的apif又被重写成api，如何才能让请求匹配到配置的第二个代理服务器地址呢
![配置代理服务器](https://github.com/user-attachments/assets/7f8df82c-de74-4a14-97e5-0746835c4c0e)

**Comment by i1619khz** [comment]
前缀不要一样的，/api /apif，都会匹配到/api，/api的配置排在前面就会有这种问题，改成其他的前缀

**Comment by zsyhb** [comment]
> 前缀不要一样的，/api /apif，都会匹配到/api，/api的配置排在前面就会有这种问题，改成其他的前缀

感谢大佬指点，测试配置成功了
