### ISSUE TITLE
Unexpected extension ".scss" in @import (scss/load-partial-extension)Stylelintscss/load-partial-extension

### ISSUE THREAD

**Issue by dong-lufei** [HalseySpicy/Geeker-Admin#486]
How to fix this syntax prompt problem：

**Comment by dong-lufei** [comment]
![屏幕截图 2024-08-11 175526](https://github.com/user-attachments/assets/83f39225-03eb-402b-9a47-16d5e53322dd)

**Comment by limuen** [comment]
> ![屏幕截图 2024-08-11 175526](https://private-user-images.githubusercontent.com/63916062/356865798-83f39225-03eb-402b-9a47-16d5e53322dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDQzODYsIm5iZiI6MTcyNjY0NDA4NiwicGF0aCI6Ii82MzkxNjA2Mi8zNTY4NjU3OTgtODNmMzkyMjUtMDNlYi00MDJiLTlhNDctMTZkNWU1MzMyMmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3MjEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNjA5YTQ0MzcyYzhjMTc3OTkzZmE1ODY3MDBiMGY3MTI3ZTAwYzZjNmRiMGNhZTNlNDE3OGY3MDhiNjc1MTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DOL0AJCTyixH_DIIOzE-KBrsdPVm408BfGApHemLQAo)

在.stylelintrc.cjs添加"scss/load-partial-extension": null

或者直接当前文件保存，会默认修复
