### ISSUE TITLE
路由中定义参数的时候,跳转会有问题

### ISSUE THREAD

**Issue by zhengkunwang223** [HalseySpicy/Geeker-Admin#49]
![image](https://user-images.githubusercontent.com/31820853/184116220-46c27280-dcc9-40e5-8886-5a8520c9bacc.png)

这段代码判断
如果 path: '/home/:id', 是这种类型,会跳转到403

**Comment by Jeffrey-mu** [comment]
你这个跳转路径有问题吧 应该是 /path?id=xx

**Comment by zhengkunwang223** [comment]
> 你这个跳转路径有问题吧 应该是 /path?id=xx

![image](https://user-images.githubusercontent.com/31820853/184293944-9de77d8f-ad7f-4e50-9996-b967ca70ac27.png)
我是用的这种路径

**Comment by denganjia** [comment]
已优化此功能
