### ISSUE TITLE
【性能优化】全局引入Element Plus组件的问题

### ISSUE THREAD

**Issue by xb001130** [HalseySpicy/Geeker-Admin#491]
如果用到的组件比较少，全局引入会把没用到的组件也打包进去，直接影响到页面的响应速度。
我改用了自动引入组件的插件，你的搜索组件也没法用了，在设计之初就没有考虑到这些问题，改不改是你的事，反正我是不会用这套模板的！

**Comment by HalseySpicy** [comment]
谢谢你，幸好你没用 😓
