### ISSUE TITLE
ProTable如何设置每页显示多少条？

### ISSUE THREAD

**Issue by kgdxpr** [HalseySpicy/Geeker-Admin#504]
现在默认为每页显示10条，我的每个页面默认显示条数都会不一样，我该如何写，谢谢。

**Comment by suyuan0** [comment]
在hooks/useTable里面可以修改默认展示条数
src/hooks/useTable.ts
![image](https://github.com/user-attachments/assets/302788f1-b550-4867-9117-900bf1fa0f35)
