### ISSUE TITLE
关于表格自适应高度，溢出内容内部滚动的问题

### ISSUE THREAD

**Issue by xiaoz-work** [HalseySpicy/Geeker-Admin#506]
请问是怎么使用 flex 布局达到这个效果的
el-table是必须给父容器或者自身设置高度才能实现内部滚动的
我自己也使用flex布局并设置了 flex-1属性，内容未溢出的情况下能够使表格自适应高度，但只是类似于min-height的效果，溢出内容依然会撑开表格高度，求解答！！！！

**Comment by MissYooo** [comment]
试试  overflow: hidden;
