### ISSUE TITLE
树形table数据

### ISSUE THREAD

**Issue by workCleaner** [HalseySpicy/Geeker-Admin#508]
看了官网的树形表格
地址：https://admin.spicyboy.cn/#/proTable/treeProTable
用户状态是启用的搜索方式
我看到总搜索条件是18怎么两页数据都是十个数据
![1](https://github.com/user-attachments/assets/3630f14d-4b2d-46b0-ab81-89478b643297)
m没太搞明白这个树形的实现逻辑
可以讲解一下吗

**Comment by HalseySpicy** [comment]
mock 数据

**Comment by workCleaner** [comment]
> mock 数据

好的  感谢
