### ISSUE TITLE
mock相关接口地址均500

### ISSUE THREAD

**Issue by AffiNiNy** [HalseySpicy/Geeker-Admin#512]
![image](https://github.com/user-attachments/assets/b8352354-c9c6-4f23-8682-53c656d6cb37)
如图； 
注释掉登录方法后, list 接口 500
![image](https://github.com/user-attachments/assets/14714b07-6ae4-4197-a34b-20ea3be8fc87)

这是mock那边删库跑路吗?

**Comment by HalseySpicy** [comment]
easymock 挂了，等我切到 apifox
