### ISSUE TITLE
复杂ProTable展开合并的第一行后，第二行数据样式会错乱

### ISSUE THREAD

**Issue by zk-Nicole** [HalseySpicy/Geeker-Admin#513]
![企业微信截图_17297337993773](https://github.com/user-attachments/assets/bc7173c2-dc4b-4a0d-b6c1-6b07bfb9633e)

**Comment by HalseySpicy** [comment]
element 就这样

**Comment by zk-Nicole** [comment]
好的，谢谢。大佬，有时间的话，能考虑在这个项目中修复一下么？

> element 就这样

**Comment by HalseySpicy** [comment]
> 好的，谢谢。大佬，有时间的话，能考虑在这个项目中修复一下么？
> 
> > element 就这样

得去给 element 提 issues 哦，
