### ISSUE TITLE
Tree Filter 组件怎么在自己的项目中引用？

### ISSUE THREAD

**Issue by tripitakav** [HalseySpicy/Geeker-Admin#52]
后端开发不太懂前端，有个功能很符合这个组件，能像UI库一样直接引入吗?

**Comment by HalseySpicy** [comment]
你好，这个组件直接引入使用就好了，这里有个示例你可以看看：
![image](https://user-images.githubusercontent.com/51069636/186359556-2b969d3d-a024-4548-9ff0-b2071e74084b.png)
