### ISSUE TITLE
表格Column配置formatter无效

### ISSUE THREAD

**Issue by changyiming** [HalseySpicy/Geeker-Admin#524]
// 表格配置项
const columns: ColumnProps[] = [
  { prop: "VAL", label: "名称", width: 200, align: "left", search: { el: "input" } },
   {
    prop: "CJRQ",
    label: "创建时间",
    width: 120,
    //type: "date",
    formatter: function (row, cell, cv, i) {
      console.log(row, cell, cv, i);
      return dayjs(row.CJRQ).format("YYYY-MM-DD HH:mm:ss");
    }
  }
];

formatter 格式化回调函数不会被执行

**Comment by HalseySpicy** [comment]
使用 render 即可
