### ISSUE TITLE
提个小建议：图标选择器组件的dialog内部可以使用grid布局

### ISSUE THREAD

**Issue by Zong-FatStar** [HalseySpicy/Geeker-Admin#53]
我之前也写过图标选择器，发现其中图标的名称有自动换行的问题，不美观
发现element文档中是用grid布局实现的，自己试了一下，可以比较好的解决

**Comment by HalseySpicy** [comment]
还没咋写过 grid 布局，后面有空学习下，或者大佬可以给我提个pr

**Comment by HalseySpicy** [comment]
已更新为 grid 布局
