### ISSUE TITLE
proForm 动态赋值问题

### ISSUE THREAD

**Issue by muchenfine** [HalseySpicy/Geeker-Admin#55]
如果配置表单项columns，如果columns里的某个select的数据是后台接口返回的， 应该如何操作，通过column[2] 这种索引方式吗  ？

**Comment by HalseySpicy** [comment]
你好👋，这个问题已经解决了，拉取最新代码在 useComponent 页面就能看到使用事例，enum 可以直接传获取数据的方法，可以在 searchProps 指定keyname

**Comment by HalseySpicy** [comment]
建议看下这篇文章：https://juejin.cn/post/7096347542090153997， 写得很好。

**Comment by HalseySpicy** [comment]
建议使用 ref
