### ISSUE TITLE
打包后体积过大

### ISSUE THREAD

**Issue by yansh97** [HalseySpicy/Geeker-Admin#58]
作者您好，在clone最新的项目（commit：c95a1c054ee9eacae470bcaae7574d5c989b86a2）到本地，运行npm I安装依赖后运行npm run build:pro后构建的包有7M大小，请问这个是正常的嘛？还是需要进一步配置？

**Comment by HalseySpicy** [comment]
你好👋，图片和字体占了差不多一大半，实际大小只有2-3M，如果不用图片和字体可以删除，数据大屏模块很大

**Comment by yansh97** [comment]
谢谢作者！
