### ISSUE TITLE
echarts实例不应声明为响应式对象

### ISSUE THREAD

**Issue by non-one** [HalseySpicy/Geeker-Admin#61]
在组件`views/dashboard/dataVisualize`中，index.vue中使用
```
const dataScreen: ChartProps = reactive({
	chart1: null,
	chart2: null
});
```
来保留初始化后的echarts对象，但是根据echarts issue中的描述，不建议声明为响应式对象(https://github.com/apache/echarts/issues/17619#issuecomment-1237368603)
自己在使用过程中也遇到tooltip组件异常的情况，简单的解决办法是将`reactive`删去。

**Comment by HalseySpicy** [comment]
谢谢老哥建议，已更改😄
