### ISSUE TITLE
{ headers: { noLoading: true } }会覆盖默认headers

### ISSUE THREAD

**Issue by fy5220** [HalseySpicy/Geeker-Admin#65]
{ headers: { noLoading: true } }会覆盖默认headers

**Comment by quruonan** [comment]
+1，还会产生跨域问题，去掉{ headers: { noLoading: true } }就没事儿了

**Comment by denganjia** [comment]
> { headers: { noLoading: true } }会覆盖默认headers

我这边没有发现这个问题，会不会是你用的之前的版本。
![image](https://user-images.githubusercontent.com/46669447/199682140-079ac510-89cc-4e0b-bc57-79ba160d996b.png)
![image](https://user-images.githubusercontent.com/46669447/199682196-36892227-336a-457d-b15d-ad3747f64f5a.png)
