### ISSUE TITLE
proTable建议

### ISSUE THREAD

**Issue by rookieCheer** [HalseySpicy/Geeker-Admin#67]
首先效果确实很好 很强大  
但是  protable  这块
1 有没有感觉配置太繁琐了  对新手使用有点困难，可否再给个详细问博客文章
2 我一个页面 感觉需要引入好多的依赖才可以 有点眼花缭乱的。

可能还是我太菜了

一个稍微懂点前端的后端程序员

**Comment by HalseySpicy** [comment]
https://juejin.cn/post/7094890833064755208

**Comment by HalseySpicy** [comment]
Pro-Table 组件使用属性透传重构完成，文档在这里查看：https://juejin.cn/post/7166068828202336263
