### ISSUE TITLE
提一个关于tab的小建议

### ISSUE THREAD

**Issue by fancy-xie** [HalseySpicy/Geeker-Admin#69]
![image](https://user-images.githubusercontent.com/35621738/197920479-a23ad666-7225-4299-a94f-21103af36a11.png)
现在标签栏使用的是el-tabs来实现，在点击之后可以使用左右方向键来切换页面，而且会出现一个难看的框框。就算用`@keydown.capture.stop.prevent`禁用了键盘切换也还是会出现框框。建议像其他模板一样用其他方式写一个标签栏，感激不尽。

**Comment by HalseySpicy** [comment]
🤣🤣 你不说，我还不知道能用键盘操控，哈哈哈哈哈哈，后面有空我会重新写个

**Comment by ColinSix** [comment]
绝绝子了, 我这涨了一波姿势, 哈哈哈哈

**Comment by denganjia** [comment]
这是因为element给tabs加了focus-visible状态下的样式。
可以自行覆盖
![image](https://user-images.githubusercontent.com/46669447/205253660-abdbcd22-9923-48d3-a174-87b436f95b4a.png)
