### ISSUE TITLE
老哥几年的经验 我初学习v3ts的时候可没能写这么牛逼！

### ISSUE THREAD

**Issue by Loveyless** [HalseySpicy/Geeker-Admin#7]
顺便问问有用了那些优化 可以写到readme里面我也想知道 主要感觉这个网页很快 但是我自己写后台的时候没多少东西还会卡卡的

**Comment by Loveyless** [comment]
加了！我来狠狠的克隆研究你的代码

**Comment by klower** [comment]
代码写的挺好，正在学习中。。。 作者能否基于angular 弄一个框架出来呢 @HalseySpicy

**Comment by HalseySpicy** [comment]
> 代码写的挺好，正在学习中。。。 作者能否基于angular 弄一个框架出来呢 @HalseySpicy

你好，angular 目前还没了解过，暂时也不会使用。

**Comment by yang-xianzhu** [comment]
两年写开源，强啊大佬
