### ISSUE TITLE
分类筛选组件功能

### ISSUE THREAD

**Issue by Jeffrey-mu** [HalseySpicy/Geeker-Admin#70]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/66287770/198233479-dced4511-8fbe-4ae4-aee2-51a09105fb4f.png">
如图
单选： 全部应该为`清空`
多选：选择全部应该全部高亮，并且返回所以状态

如通过 可以提交pr

**Comment by jackbrens** [comment]
单选：选择 “全部” 为什么要清空多选？
多选：选择 “全部” 不需要所有的类型都高亮吧，淘宝的分类筛选也不没这样的吧

**Comment by HalseySpicy** [comment]
你好，当前逻辑不存在问题，单选和多选是互不关联的两个模块

**Comment by Jeffrey-mu** [comment]
逻辑正确 我理解错误



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jackbrens ***@***.***&gt;
发送时间: 2022年10月28日 09:38
收件人: HalseySpicy/Geeker-Admin ***@***.***&gt;
抄送: Jeffrey ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [HalseySpicy/Geeker-Admin] 分类筛选组件功能 (Issue #70)





 
单选：选择 “全部” 为什么要清空多选？
 多选：选择 “全部” 不需要所有的类型都高亮吧，淘宝的分类筛选也不没这样的吧
