### ISSUE TITLE
isLink 的逻辑不太合适

### ISSUE THREAD

**Issue by cdk8s-zelda** [HalseySpicy/Geeker-Admin#79]
- 因为是小问题，我就自己改了不提 PR 了。
- 不合理的理由是：右侧菜单都是从接口中拿到的，外链链接大部分场景都是动态添加出来的，而 Geeker-Admin 需要先预设好一个 views 页面或者 component。
- 合理的方式是：只要是 isLink，则不需要改变路由，直接 open 链接即可

**Comment by HalseySpicy** [comment]
感谢提出，下次更新会优化😀
