### ISSUE TITLE
调试时候行数定位跟source上对不上

### ISSUE THREAD

**Issue by zcvvvbb** [HalseySpicy/Geeker-Admin#8]
![image](https://user-images.githubusercontent.com/37097980/169634137-8cc657f5-69ff-453e-a127-ca1ef0e696cf.png)
兄弟，这问题知道啥原因不，我另外的vite项目好像也这样。

**Comment by changzhenlin** [comment]
这不都是9行吗

**Comment by zcvvvbb** [comment]
@changzhenlin 上面的console在11行，另外我找到原因了是vite-plugin-vue-setup-extend这个插件导致的。

**Comment by Corgis** [comment]
vite-plugin-vue-setup-extend 这个插件可能会导致这个问题
