### ISSUE TITLE
searchParam 想要重新赋值的疑问

### ISSUE THREAD

**Issue by cdk8s-zelda** [HalseySpicy/Geeker-Admin#80]
## 问题描述

```
搜索条件比较复杂，可能需要对某个输入框的内容进行编辑、拆解、加密之后再请求。
所以我自定义了自己的 searchParam

<el-form-item label="角色名称 :" prop="roleName">
    <el-input v-model="searchParam.roleName" placeholder="请填写角色名称" clearable></el-input>
</el-form-item>

<ProTable
	ref="proTable"
	title="用户列表"
	:columns="columns"
	:requestApi="getSysRoleList"
	:initParam="initParam"
	:dataCallback="dataCallback"
	:searchParam="searchParam"
>

let searchParam = reactive({
	roleName: "这是默认值"
});

const searchFunction = () => {
    // 假设这里我对 input 值做特殊处理
    //  测试发现：proTable.value.searchParam = searchParam;  不会把我的搜索参数请求到后台
	proTable.value.searchParam = searchParam;
	proTable.value.getTableList();
};

请求，我应该如何编写才可以补充 searchParam??


```

**Comment by HalseySpicy** [comment]
你好，可以参考 useSelectFilter 模块，给 ProTable 传 initParam 参数，initParam 更新会自动触发获取列表事件
![image](https://user-images.githubusercontent.com/51069636/203192851-038719e9-f2c0-40c9-89a5-1da21441405a.png)

**Comment by HalseySpicy** [comment]
你可以给 el-input 绑定 model-value 而不是 v-model，然后使用 @change 事件在失去焦点时在改变其 value 值

**Comment by cdk8s-zelda** [comment]
> 你可以给 el-input 绑定 model-value 而不是 v-model，然后使用 @change 事件在失去焦点时在改变其 value 值

- 非常感谢作者，我试试看！！！

**Comment by cdk8s-zelda** [comment]
- 另外有一个建议：我现在不用 protable 的 search 属性功能，是自己把搜索 div 复制出来的。
- 理由是：很多时候搜索的交互不单单只是简单的输入，选择，还会有一些逻辑处理，比如我需要加密传参，需要做字符串的某种处理，需要为了额外增加一些参数。我不怕代码量大，因为现代的前端都是有规律的， 发现规律写个生成器模板都可以快速生成代码，就怕不灵活，所以我个人建议封装的组件是尽可能灵活，而不是齐全。（我是做后端的！）

**Comment by tlerbao** [comment]
@cdk8s-zelda 这就是我建议的不要封装过度，纵使ProTable很强大，也难免实现不了一些个性化需求。

官方在有ProTable的前提下，内置个简单的类似 useTableList 的 hook，实现基本的数据获取封装就行了，然后表格结构 搜索部分什么的都由用户自己灵活自定义，如果可以的话 还可以有简单的useCreate/useEdit 这两个可以做成一个，这样的话ProTable用来做百分之80的需求  useTableList/useStore 用来做百分之15的curd，及特殊的极其个性的 剩下5%用户完全自己写哈。

**Comment by HalseySpicy** [comment]
目前最好的方法可以这样写，可以对请求参数做一切操作，包括加密任何操作
![image](https://user-images.githubusercontent.com/51069636/203209072-4806a61b-07c2-4007-a4eb-0cf151e96c7d.png)
![image](https://user-images.githubusercontent.com/51069636/203209107-2c00e894-2ceb-4401-bba6-49f44e372fa1.png)
![image](https://user-images.githubusercontent.com/51069636/203209205-eac36142-551d-4d9e-8a71-ef66c06f6ad0.png)

**Comment by HalseySpicy** [comment]
> @cdk8s-zelda 这就是我建议的不要封装过度，纵使ProTable很强大，也难免实现不了一些个性化需求。
> 
> 官方在有ProTable的前提下，内置个简单的类似 useTableList 的 hook，实现基本的数据获取封装就行了，然后表格结构 搜索部分什么的都由用户自己灵活自定义，如果可以的话 还可以有简单的useCreate/useEdit 这两个可以做成一个，这样的话ProTable用来做百分之80的需求 useTableList/useStore 用来做百分之15的curd，及特殊的极其个性的 剩下5%用户完全自己写哈。

之前公司项目就是这样做的，可能目前公司业务需求不太复杂， 最后就把 search 模块封装到了一起。感谢提出建议

**Comment by cdk8s-zelda** [comment]
@HalseySpicy 

> 目前最好的方法可以这样写，可以对请求参数做一切操作，包括加密任何操作 ![image](https://user-images.githubusercontent.com/51069636/203209072-4806a61b-07c2-4007-a4eb-0cf151e96c7d.png) ![image](https://user-images.githubusercontent.com/51069636/203209107-2c00e894-2ceb-4401-bba6-49f44e372fa1.png) ![image](https://user-images.githubusercontent.com/51069636/203209205-eac36142-551d-4d9e-8a71-ef66c06f6ad0.png)


- 我采用了其他方式，改了这里：useTable.ts

```
const getTableList = async (params?: any) => {
	try {
		// 先把初始化参数和分页参数放到总参数里面
		Object.assign(state.totalParam, initParam, params, isPageable ? pageParam.value : {});
		let { data } = await api(state.totalParam);
		dataCallBack && (data = dataCallBack(data));
		state.tableData = isPageable ? data.datalist : data;
		// 解构后台返回的分页数据 (如果有分页更新分页信息)
		const { pageNum, pageSize, total } = data;
		isPageable && updatePageable({ pageNum, pageSize, total });
	} catch (error) {
		console.log(error);
	}
};
```
