### ISSUE TITLE
创建时间搜索存在bug

### ISSUE THREAD

**Issue by zjh020719** [HalseySpicy/Geeker-Admin#84]
![image](https://user-images.githubusercontent.com/71053741/204097274-89575ba8-4915-4e42-acc7-352e7eab63a8.png)

**Comment by zjh020719** [comment]
同时输入框输入时间,起始或者结束时间会自动改变为输入时间的前或后一个月

**Comment by HalseySpicy** [comment]
你好，暂时没明白你说的是什么意思，或许你可以看看 element-plus 官方存在这个问题吗

**Comment by denganjia** [comment]
> 同时输入框输入时间,起始或者结束时间会自动改变为输入时间的前或后一个月

这个问题Element Plus也存在，属于是Element的问题
