### ISSUE TITLE
打包发布后第一次加载页面全屏无法点击（点击无任何反应）？

### ISSUE THREAD

**Issue by TomSonghang** [HalseySpicy/Geeker-Admin#89]
打包发到正式，登录进去之后点击任何区域都没有反应，按F5刷新之后就好了，这个大概会是什么原因导致的？给个方向我去找找问题大佬

**Comment by HalseySpicy** [comment]
有报错吗，或者你这边可以直接打包在本地启服务呢？可以试试直接拉取我最新的代码打包试试
