### ISSUE TITLE
切换到图标选择器菜单出现vite报错

### ISSUE THREAD

**Issue by MARIOMARUI** [HalseySpicy/Geeker-Admin#90]
![image](https://user-images.githubusercontent.com/48650709/205434613-5946df64-24a5-4515-9de1-254eecca9fdd.png)

拉取最新的代码，换了一台电脑也会导致报错，但是在线地址没有问题

**Comment by MARIOMARUI** [comment]
希望作者排查一下

**Comment by HalseySpicy** [comment]
你好，我这本地没有错误，或许你可以把 node_modules 删掉，重新安装试试
![6b5c1badd7780f52063175b23644756](https://user-images.githubusercontent.com/51069636/205441512-fe1e2b7d-97fd-400a-a931-2c8cb06c3afe.png)
![eacd9f321cfcf1a95b4490ef0208ba1](https://user-images.githubusercontent.com/51069636/205441518-e7931b66-30f9-4640-b28a-49e2d08643ce.png)

**Comment by MARIOMARUI** [comment]
好的，还有cleaarble属性是不生效的，因为focus方法会覆盖掉，建议删除该属性
