### ISSUE TITLE
ProTable 列填充Switch好像不显示disable的文字，麻烦大佬确认下

### ISSUE THREAD

**Issue by zhouxx** [HalseySpicy/Geeker-Admin#92]
大佬我又来了，哈哈~

我修改了用户状态的render，如下图：
![image](https://user-images.githubusercontent.com/9975353/205435227-16a697ad-d3e6-40c7-84a7-fb2202776b2c.png)

然后显示的效果如下：
![image](https://user-images.githubusercontent.com/9975353/205435254-bc91b488-0dcc-42d9-b3b0-550e803db8e4.png)

在常规form里好像是正常的：
![image](https://user-images.githubusercontent.com/9975353/205435289-d020114d-cc7e-4236-886b-a6fa1e9a9801.png)

element plus版本2.2.26

麻烦确认下，是本身element官方的问题，还是ProTable引发的问题

**Comment by MARIOMARUI** [comment]
你应该使用  inactive-text="否" 而不是使用三元表达式

**Comment by zhouxx** [comment]
@MARIOMARUI   明白了，明白大佬的写法了，谢谢了~
