### ISSUE TITLE
ProTable搜索表单中的enum为何不提供透传？

### ISSUE THREAD

**Issue by taodamiao** [HalseySpicy/Geeker-Admin#93]
如题，ProTable里配置ColumnProps，el-tree时配置enum时，只提供传数组或者promise。当表格插槽也需要用到枚举值时，就需要再次请求接口获取字典了。
场景：
ProTable筛选用户状态status，配置enum传递的是promise获取用户状态字典数据方法；之后我需要用插槽#status 根据字典里的一些额外加点样式， 插槽里只能获取到row原数据，针对这种情况，我如何获取到enum数据？

我觉得最好的方式，是在使用ProTable组件时，外面提供ref给enum，又或者是promise。当遇到我上面的场景是，用透传。

**Comment by denganjia** [comment]
> 如题，ProTable里配置ColumnProps，el-tree时配置enum时，只提供传数组或者promise。当表格插槽也需要用到枚举值时，就需要再次请求接口获取字典了。 场景： ProTable筛选用户状态status，配置enum传递的是promise获取用户状态字典数据方法；之后我需要用插槽#status 根据字典里的一些额外加点样式， 插槽里只能获取到row原数据，针对这种情况，我如何获取到enum数据？
> 
> 我觉得最好的方式，是在使用ProTable组件时，外面提供ref给enum，又或者是promise。当遇到我上面的场景是，用透传。

ProTable组件->index.vue文件中第148行，保存了columns中所有的enum的结果，你可以在index.vue中第234行将它暴露给外层。

**Comment by taodamiao** [comment]
> > 如题，ProTable里配置ColumnProps，el-tree时配置enum时，只提供传数组或者promise。当表格插槽也需要用到枚举值时，就需要再次请求接口获取字典了。 场景： ProTable筛选用户状态status，配置enum传递的是promise获取用户状态字典数据方法；之后我需要用插槽#status 根据字典里的一些额外加点样式， 插槽里只能获取到row原数据，针对这种情况，我如何获取到enum数据？
> > 我觉得最好的方式，是在使用ProTable组件时，外面提供ref给enum，又或者是promise。当遇到我上面的场景是，用透传。
> 
> ProTable组件->index.vue文件中第148行，保存了columns中所有的enum的结果，你可以在index.vue中第234行将它暴露给外层。

这样方式不行，父组件永远拿到一个空的map，没法做到响应式，得增加一个更新方法才可以，子组件通知父组件更新，父组件再更新值，这样略显麻烦，有没有一种比较优雅的方案？
